### ISSUE TITLE
returning user should see his videos on the upload page

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#108]
This means that when the user arrives on the uploader page later (let's say the next day) he should see the list of videos that hare his.

In other words, on landing, we want to populate the `videos` list in the state with all videos on which he is an owner. 

This issue depends on having `vids.search` available on paratii-lib, which is tracked here: https://github.com/Paratii-Video/paratii-lib/issues/35

**Comment by bent0b0x** [comment]
@jellegerbrandy I don't see this mentioned in that `paratii-lib` issue, but how do we search for all videos uploaded by a particular user/address?

**Comment by eliawk** [comment]
```
const address = paratii.config.account.address
paratii.core.vids.search({owner: address)
```

**Comment by eliawk** [comment]
https://github.com/Paratii-Video/paratii-portal/pull/235
