### ISSUE TITLE
Do not build everything in a single bundle.js

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#11]
At the moment, `yarn build` packages all data, including static assets like images, and source maps of code, etc, in a single `bundle.js`. 

This is not scaleable and f*ks up caching, we need an output in which we can serve assets directly (bu apache/nginx) from a single `static` folder

In other words: I liked to output of `react-scripts build` much better (cf commit d56d82f1bd66bb53ac456859446626f0fb9d73fc)

**Comment by bent0b0x** [comment]
@jellegerbrandy can this be closed or are there addl. parts of the build process that you'd like to see improved?

**Comment by jellegerbrandy** [comment]
Closing this for now - it is really an optimization matter, and that is something we should not bother with too much at this early stage.
