### ISSUE TITLE
Make "play/pause" button work on media player in the "play page"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#113]
- [ ] Pause Button
  - go to http://localhost:8080/play/foo
  - click on play (wait wait wait)
  - clicking on pause icdon in the player does nothing. 
  - Further observations:
    - clicking on the video _does_ pause. 
    - space bar does not pause
    - in the embedded version, pause icon is not working either, but space bar does
     
![resizebug](https://user-images.githubusercontent.com/7697924/35887998-31de97a4-0b64-11e8-8653-d14f90d427b9.gif)

**Comment by bent0b0x** [comment]
Who needs a working pause button!

😝  will look at this tonight

**Comment by bent0b0x** [comment]
Converted this issue to be more general so I can track progress on the large task of adding to the player experience

**Comment by bent0b0x** [comment]
@jellegerbrandy I cannot reproduce the issue w/ the pause button not working. Can you send a gif (in case I am doing something slightly differently from you)

**Comment by jellegerbrandy** [comment]
@bent0b0x  is this issue still used, or shall we close it?

**Comment by felipegaucho** [comment]
Still valid. I tried to be more precise in the issue title (@jellegerbrandy, @bent0b0x  !).
Too many small issues will appear on building the larger player experience.

![gif player](https://user-images.githubusercontent.com/26517120/36601852-f7966be2-1894-11e8-8869-b0704ce89f70.gif)

**Comment by jellegerbrandy** [comment]
This works for me now
