### ISSUE TITLE
Create voucher component (and page)

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#115]
This is a simple form that has a single input field for inputting a string, and a sumbit button ("redeem voucher"). 

It should call `paratii.eth.voucher.redeem(myvoucherstring)`, which will returna  promise. Success also means that the balance of the user is updated.

For now, we can show this on a route to `/voucher`.

See https://github.com/Paratii-Video/paratii-lib/issues/103

**Comment by jrgarou** [comment]
@eliawk the component: https://github.com/Paratii-Video/paratii-portal/commit/3fb6cb6cb34a3fc1007c0d35ab14ac12fe4764b5

**Comment by jellegerbrandy** [comment]
It's working!
