### ISSUE TITLE
create component in the player to show user address and balance

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#116]
This is the small popup that you see if you click on the user icon on the top right.

**Comment by bent0b0x** [comment]
I am working on this, FYI

**Comment by jellegerbrandy** [comment]
I've made a ugly placeholder for a Wallet page, which is accessible clikcing on the user icon. I wanted a place where the user at least can see his addres, and from which we later will add the "how to backup and restore your wallet"a nd other stuff.

@pedrocasa , we shoudl talk about this in the next days :-)

**Comment by jellegerbrandy** [comment]
The UI design for the current page is https://xd.adobe.com/view/ac964a03-32b8-40ed-a868-4a849aecd855/screen/dccc15ef-eeec-4e0f-afc4-dec45eb05495/P-10

**Comment by jellegerbrandy** [comment]
movign this to backlog as it is not blocking

**Comment by felipegaucho** [comment]
If @bent0b0x's deep in the media player maybe @jrgarou can help tackle this issue, this week?

**Comment by jellegerbrandy** [comment]
closing this. We have a placeholder now, and will do the rest as part of  https://github.com/Paratii-Video/paratii-portal/issues/363
