### ISSUE TITLE
Uploader - PTI Guide Component

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#119]
Create the slide show component for the PTI Guide

<img width="899" alt="schermata 2018-02-07 alle 11 19 34" src="https://user-images.githubusercontent.com/362016/35911005-cdea4938-0bf8-11e8-9821-633d8f7693e7.png">

**Comment by jrgarou** [comment]
PR for the PTI Guide with texts https://github.com/Paratii-Video/paratii-portal/pull/169
