### ISSUE TITLE
Uploader - manage user wallet

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#121]
We need to know how many PTI there is in the user wallet to let the user upload a new video

**Comment by jellegerbrandy** [comment]
You can get the account from `paratii.config.account.address`, and then pass it to this function to get the balance: https://github.com/Paratii-Video/paratii-lib/blob/dev/docs/paratii-eth.md#ethbalanceofaccount-symbol

**Comment by jellegerbrandy** [comment]
Also see #116

**Comment by bent0b0x** [comment]
@eliawk I'm planning on tackling this (unless you're already on it) for my branch where we will display balance in video popover. 

It is my understanding that the eth/pti balances could change all of the time. For that reason, simply fetching this information and storing it in `redux` throughout the life of the `app` maybe isn't the best idea. Here is what I am thinking:

- do store balance in the `redux` state
- when we render balance in the UI, pull the value from `redux`
- whenever we need an up to date balance, make sure to `dispatch` a new thunk that will get the true balance from `paratii-lib` and update the `redux` store.

This way, we will always have some value for balance in the `store` but when we need an up-to-date value any code can `dispatch(updateBalances())`

Thoughts?

**Comment by jellegerbrandy** [comment]
Seems perfect to me

**Comment by eliawk** [comment]
@bent0b0x go ahead on this!
