### ISSUE TITLE
Responsive components

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#123]
@jrgarou We need to make our components responsive.
https://medium.com/styled-components/how-to-create-responsive-ui-with-styled-components-c6b71a3ce172

<img width="548" alt="schermata 2018-02-08 alle 11 39 31" src="https://user-images.githubusercontent.com/362016/35968627-c29a98a4-0cc4-11e8-9fae-7318741d2053.png">

@bent0b0x do you any better clue to handle that?

**Comment by jrgarou** [comment]
@eliawk Our comonents isn't gonna be like this. But will work 😄 
this is login page(my local)
![image](https://user-images.githubusercontent.com/320157/35972222-1309452c-0cb8-11e8-9c9c-a77d71cd34a0.png)

Where is this template exactly? what is this print?

**Comment by jellegerbrandy** [comment]
slightly OT with respect to this issue, but important that you all know this:  We are not doing log in with username and password anymore, like we dd with the meteor app. We use this instead: .https://github.com/Paratii-Video/paratii-portal/wiki/Portal-Specs:-wallet-handling

**Comment by jrgarou** [comment]
@eliawk Our _cards_ are pretty simple to deal with.
```
export const CardContainer = styled.div`
  display: flex;
  justifyContent: center;
`

const CardWrapper = styled.div`
  flex: 1 1 100%;
  min-width: ${props => props.full ? '' : '388px'};
  max-width: ${props => props.full ? '' : '33%'};
`
```

The `full` get all space(we could set a max value) not used by others cards(min-width 388px and max-width 33%). 

I'm using `margin` **props** to deal with space between them: `<Card full margin="0 0 0 25px">`. But I'll change to pre-defined values: `<Card marginLeft  marginRight>`
