### ISSUE TITLE
Investigate failing login test

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#125]
👇 this test is skipped because it was failing

https://github.com/Paratii-Video/paratii-portal/pull/118/commits/6bc19dfaea3582e61b1732ed4f6d19cc390abb5d#diff-97a13b2ee82fb9bdf221ada16588429e

**Comment by jellegerbrandy** [comment]
Yes, those tests are migrated from the old version of the player, and outdated. They are not particularly expected to work as is.
