### ISSUE TITLE
Video not found

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#134]
If the video don't exist we need to show an error to the user and don't call `this.createPlayer(ipfsHash)` in `componentWillReceiveProps` function.

The error is now managed in the state with 

```
"xxx": {
        "fecthStatus": {
          "name": "failed",
          "data": {
            "error": "No video with id 'xxx' was registered"
          }
        }
      }
```

**Comment by eliawk** [comment]
@pedrocasa how do we manage error in FE?

**Comment by pedrocasa** [comment]
I think when this happens we should have a link to the user go back for the first page ( UP02)

here's the design of it 

![up02 3](https://user-images.githubusercontent.com/30123644/36050650-7604437c-0dce-11e8-9d8b-ceec149bf792.png)
