### ISSUE TITLE
optimize when IPFS is loaded 

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#138]
At the moment, the ipfs node is initialized only at the moment that we click "play". This makes the UX very slow. This should be already mitigated with the new mediaplayer version (that loads from the gateway when the file is not ready yet), but we can do better:

* we shoudl initialize the IPFS as early as possible in the application lifetime (this is also important for our network to function as well as possible)
* Check that we never do double work. (For example, we should never initialize the node twice, make sure that the ipfs database does not change between sessions)
* [this is hard:] perhaps we can do some prediction of user behavior and prefetch some data (for example, if a user just uploaded a file, we can expet he will play the results)

**Comment by jellegerbrandy** [comment]
@ya7ya , thoughts, additions?

**Comment by ya7ya** [comment]
Hey @jellegerbrandy , yesterday's upgrades added to [`hlsjs-ipfs-loader`](https://github.com/ya7ya/hlsjs-ipfs-loader/pull/1/files) should take care of this, I'm also looking at more optimizations. also checkout out https://github.com/Paratii-Video/paratii-mediaplayer/pull/35/files

**Comment by jellegerbrandy** [comment]
Yes. But these optimizations should happen _before_ the mediaplayer is created. 

A concrete use case: user arrives on the "about" page and reads the texts for a few minutes, then clicks on the "Paratii Explained" video link and watches the video.

What should happen that. In the background, while he's reading a stupid text page and his browser is just doing nothing, we do as much of  the work necessary to have the video start playbing as soon as he click on it.

As I understand it, these kind of things are not covered by your upggrade (but correct me if I'm wrong)

**Comment by ya7ya** [comment]
you are correct, and this is something I'm actively working on 👍 

side note: the mediaplayer is ready to take an already initiated IPFS node so once we do the edits to the portal (where the paratiiIPFS is started on loading the page,, not the video) the integration with the mediaplayer is straightforward.

**Comment by felipegaucho** [comment]
Take the Medium post recent case, which ran 7 different ipfs instances, one for each iFrame. Would it be possible to have a single ipfs instance that all iFrames use in common? via @jellegerbrandy

**Comment by felipegaucho** [comment]
There's a dedicated issue to this optimisation https://github.com/Paratii-Video/paratii-portal/issues/675
