### ISSUE TITLE
Description input field is in fixed-width font

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#141]
Does not seem intended, so I assume it is a bug:

![image](https://user-images.githubusercontent.com/1306173/36062400-3884521e-0e6c-11e8-9848-6a6ae678a46c.png)

**Comment by jrgarou** [comment]
@jellegerbrandy I don't get it.

**Comment by milankragujevic** [comment]
@jrgarou I believe the problem is that the font is terminal-like instead of being the normal sans-serif font used everywhere else.

**Comment by jrgarou** [comment]
@milankragujevic @jellegerbrandy But this is on local? Could you tell more details?

**Comment by jellegerbrandy** [comment]
It is local, chrome, and perhaps htis helps? 

![image](https://user-images.githubusercontent.com/1306173/36111042-29385b4c-1025-11e8-85d1-788014950cbe.png)
