### ISSUE TITLE
hook up the progress bars with the event emitters

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#142]
Transocding is on "45%" (probably hardcoded in there, but woudl be good to hook up). I assume the upload progress bar is hardcoded there sas well

![image](https://user-images.githubusercontent.com/1306173/36062783-6885fb8c-0e73-11e8-9e7c-62a20e6bd2e9.png)

**Comment by ya7ya** [comment]
this might be due to the fact that the progress updates from the transcoder is ratelimited to once every 5 seconds, so if the video is very short it might update only once.

a solution to that is to change the status to 100% once the `trancoding:done` event is emitted.

**Comment by eliawk** [comment]
yes atm junior has hardcoded the value

**Comment by eliawk** [comment]
no more hardcoded, but maybe need some make up - https://github.com/Paratii-Video/paratii-portal/pull/150/files#diff-5d954b8b5e1b57f088609813c1363758R254
