### ISSUE TITLE
title field is not updated after saving

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#143]
reproduction:

* go to upload
* add a video
* fill in title and description
* click "save"
* the title field is reset to empty

(LEt's write a *test* for this :-))

**Comment by eliawk** [comment]
@jellegerbrandy i'll write a test, anyway on `dev` it's working on my local br

**Comment by eliawk** [comment]
@jelle just edit the main `should have basic flow in place`, added a control after the click on submit
