### ISSUE TITLE
uploader: show thumbnail preview on the right hand side once transcoder is done

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#144]

**Comment by eliawk** [comment]
@ya7ya now the thumbnail are working? or it was just a problem related to the video format?

**Comment by ya7ya** [comment]
@eliawk it's working but not for the test video 😢 , I been trying to to debug the issue. I'll try to get it to work before tomorrow 🤞

**Comment by eliawk** [comment]
i've changed it in the PR
https://github.com/Paratii-Video/paratii-portal/pull/150/commits/19f7ff171a07a405d445cc98d4c2c5e36e405b64#diff-5d954b8b5e1b57f088609813c1363758R181

like this
```
 if (thumbImages !== undefined) {
      thumbImage = `https://gateway.paratii.video/ipfs/${ipfsHash}/${thumbImages.get(1)}`
    } else {
      thumbImage = 'http://paratii.video/public/images/paratii-src.png'
    }
```

@ya7ya this hardcoded `https://gateway.paratii.video/ipfs/` is correct?
