### ISSUE TITLE
Create popup alerts for elements that are not working yet

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#152]
* Create the popup component (designed on 5th image here https://github.com/Paratii-Video/paratii-portal/issues/71)
* Do they show on mouseover or click (@jrgarou)?
* Functions that are not working yet:
  - Search
  - Theme switcher (bucket drop)
  - Upload from youtube (input field + "upload button")
  - Paid (on Free _vs_ paid, in the "Video Edit" component - whwen working, we can remove the text in parenthesis next to the option too)

**Comment by felipegaucho** [comment]
So we chose not to go this path for now. 

Int'd, to add the features incrementally, and next week work on stacked notifications for this matter.
