### ISSUE TITLE
Create Staking popup dialog

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#163]
This refers to "UP_08" of the uploader flow https://github.com/Paratii-Video/paratii-portal/issues/60

![image](https://user-images.githubusercontent.com/1306173/36147874-35c07bca-10ba-11e8-9d72-dbb4f8398ede.png)

This component is to call the following functions on paratii-lib: https://github.com/Paratii-Video/paratii-lib/issues/101

**Comment by jrgarou** [comment]
On https://github.com/Paratii-Video/paratii-portal/pull/171
