### ISSUE TITLE
fix bug in videoform that resets the form everytime props change

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#164]
This line is a bug: 
https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/VideoForm.js#L121

What happens is this: you are editing the form. The props change. You loose your edits. This is not good.

**Comment by eliawk** [comment]
@jellegerbrandy when the props should replace the state? just if the state field is empty?

**Comment by jellegerbrandy** [comment]
As it is now: only when the selected video is changed.
