### ISSUE TITLE
Port wallet functionality from meteor app

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#17]
Basically, this means that we will 

- [ ] port wallet handling tests from meteor app, in particular https://github.com/Paratii-Video/paratii-player/blob/dev/tests/profile.test.js and https://github.com/Paratii-Video/paratii-player/blob/dev/tests/wallet.test.js [this depends on setting up chimp tests, in issue #18 )
- [ ] port the functionality itself (but using `paratii-lib`)

**Comment by mrocha94** [comment]
Is this issue redundant: #24 and #32?

**Comment by jellegerbrandy** [comment]
Yes, indeed, thanks. Closing.
