### ISSUE TITLE
Move upload prorgress to selectors

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#173]
Is uploadProgress something that is originally coming from props/redux store? If so, I think we'll want to change this to be a selector. It could go in an UploadSelectors.js module (new if it doesn't exist).

Selectors are the place where any sort of complex (or not very very simple) logic that process/transforms/combines store data should live, IMO. Also, if this data is coming from props then there is no need to duplicate it in state.

**Comment by eliawk** [comment]
@jellegerbrandy when the props change they will be replaced by the state. but the state are update evereytime the user type anything:
https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/VideoForm.js#L145

**Comment by jellegerbrandy** [comment]
Hey are you in brasil?
You did not describe a problem.

**Comment by eliawk** [comment]
sorry @jellegerbrandy I was answering to the wrong issue...
