### ISSUE TITLE
Move to ApplicationConstants

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#174]
Can these be moved to ApplicationConstants.js and imported into AppUtils.js? It is possible we may want to use this list elsewhere. Not a big deal though, can always move later.

if (num === null || num === undefined) {
+    num = 0
+  }
+  const UNITS = ['B', 'kB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']

**Comment by jellegerbrandy** [comment]
yes they can :-)
