### ISSUE TITLE
sharing options

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#179]
In player 0.0.1 we have quite sophisticated sharing that we should port the the new player:

![image](https://user-images.githubusercontent.com/1306173/36347891-9abed81c-1463-11e8-8144-66f9fc7aaf1d.png)

**Comment by pedrocasa** [comment]
It's not very common to have sharing options on the upload page,
In my opinion, it makes more sense to have all those options on the video page

**Comment by bent0b0x** [comment]
@pedrocasa are there designs for this in the player?

**Comment by pedrocasa** [comment]
Design here https://github.com/Paratii-Video/paratii-mediaplayer/issues/39
@jrgarou
