### ISSUE TITLE
create a staging.json configuration file

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#183]
And use that in for staging.paratii.video

**Comment by jellegerbrandy** [comment]
As a remark: we are now including the configuratio (at the moment the ethereum provider + registry address, but there will be more in the future) in the build  of the portal. It would probably be easier to have a separate configuration file, so we can quickly change the config if needed. Must evauluate how to pass it along.

**Comment by bent0b0x** [comment]
I see what you are saying. Right now, if we want to update our config this requires a rebuild/deploy for it to go live, yes?

We could have the server inject our config into `window.paratiiConfig` or something. And if our config files are static assets accessible to the server we should be able to update them without any redeploying. Thoughts?

**Comment by jellegerbrandy** [comment]
closing this bc we'll never do it :)
