### ISSUE TITLE
Design.Portal Uploader corrections

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#184]
Here are some corrections for the https://staging.paratii.video/upload

The objective of this issue is to standardize our current page with the UI kits/ Web flows previously designed and

- First of all, we should use the same texts of the last comment of the issue https://github.com/Paratii-Video/paratii-portal/issues/60

Landing page

- The Cards corners need to be rounded. In the software that I'm using it's 4px rounded, but if this unit won't match visually with the front end code we may need to change this value
- The illustration of upload box needs to be updated for this one  ( link for all illustrations indicated by name of the card https://we.tl/r3kuENaQxz )
- The Input field of the forms need to be aligned to the left
- This button is not needed now and may not be needed later. If the link is correct the uploader should automatically go to the "edit" page.
- The last line of footer text of the voucher is the only text that is aligned to the right ( In the current UI kit the only texts that are aligned to the right are the support texts of the forms)
- The subtitle of the PTI guide is missing
- Need to apply the "disactivated button color" to the left arrow button of the PTI guide
- The Roboto bold font should only be used in the buttons, All other texts should be Roboto Regular
- In the last designs that I made I added a new background to the cards (just a small detail). Here is the link https://we.tl/ez1dFHRziV
- (This may be corrected when we disappear with the upload button but I'm gonna mention it here anyway) The footer of the voucher and the upload cards should have the same height.
- The footer text "Discover all about Paratii on paratii.video" should be aligned with the Paratii logo (header).

Edit Page.
- The Cards corners need to be rounded. In the software that I'm using it's 4px rounded, but if this unit won't match visually with the front end code we may need to change this value
- The Roboto bold font should only be used in the buttons, All other texts should be Roboto Regular.
- The footer text "Discover all about Paratii on paratii.video" should be aligned with the Paratii logo (header).
- The Save Data Button should be aligned with add the add another video button
- The video list footer is too big, it should be shorter
- If the Free option is the only one available right now it should already appear selected
- The transcoding loading bar is thicker than the others.
- The loading percentage of loading bars are not aligned to the other elements when it's 0%.
- The " Uploading" "Transcoding" "Data" are too big, it should have the same font size of the loading percentage
- all the info on the right side ( upload/transcoding info, fonts, bars ) is too big, it's consuming all the space.
- The name of the video still the same on the video list and header after I change it.
- Don't need to use "success" after the video uploaded we just need to show the "check" icon and the word Uploaded

**Comment by jrgarou** [comment]
On https://github.com/Paratii-Video/paratii-portal/pull/198

**Comment by pedrocasa** [comment]
I believe it's missing just two fixes

- The name of the video is not changing on the header and on the video list (I don't know if this is related to what Junior is doing right now)

- I have the feeling that there are still some bold fonts on the video list card  and on the header of the edit card (I may be wrong)
