### ISSUE TITLE
uploader tool: trascoding status is not always updated correctly

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#186]
If you upload a second video, the transcoding status will be updated for all videos instead of just the one (i.e. the status will be the same for all videos).

To reproduce:

 * upload a video that you've uploaded before and see transcoding status go green
* upload an image, and see the transcoder status for that image go to failed
* navigate back to the first video, and notice that there the transcoder is failed as well

**Comment by bent0b0x** [comment]
@ya7ya I think I have tracked this issue down to be how `paratii.ipfs.uploader` emits events. What I am seeing is that if we have called `paratii.ipfs.uploader.transocde()` multiple times, and attached event listeners (as we do [here](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/actions/UploaderActions.js#L80-L117) when a user uploads multiple videos in one session), every single `transcoder` instance's event handlers are called when one event is fired. 

By way of illustration, go to the uploader and upload one video. Note that the console logs the message `TRANSCODER DONE`. Upload a second video. Note that `TRANSCODER DONE` is logged an **additional** two times. Our transcoder event handlers for each instantiated event emitter is called even though we are only newly transcoding one video.

NOTE: this does **not** seem to be a problem w/ events on `paratii.ipfs.uploader.add()`.
