### ISSUE TITLE
Link in voucher does not do what it suggests

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#191]
This link should probably link to a contact page or just be a `mailto:` link? cc @jrgarou 

![voucher](https://user-images.githubusercontent.com/7697924/36412952-495d76a8-15ea-11e8-8500-0bdf9ef5410d.gif)

**Comment by jrgarou** [comment]
What is the link, @felipegaucho? 
The same from "request early access" from paratiisite: https://goo.gl/forms/8zJ6Q6NcqgJXHf7r2

**Comment by felipegaucho** [comment]
For now, let's just use mailto: we@paratii.video
