### ISSUE TITLE
Mission-critical uploader bugs/fixes

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#196]
- [ ] Fix spacing for "PLAY VIDEO" text
![image](https://user-images.githubusercontent.com/7697924/36436352-fffc7ce6-1631-11e8-8d65-6d2e7f5fa700.png)

- [ ] Video screenshots #190 

- [x] remove debug info from uploader

- [ ] revisit progress bars in uploader

- [ ] `/embed` route not working after upload (and all `/play` routes are `404`ing after a refresh)

- [ ] add balance to nav bar
https://user-images.githubusercontent.com/30123644/36134054-800c2590-1069-11e8-978f-4062afca978d.png

- [ ] indicate that this is a beta and we want feedback

- [ ] player sharing

cc @felipegaucho @jellegerbrandy @ya7ya 

Feel free to add to this list!

**Comment by jellegerbrandy** [comment]
Closing this in favor of using the "next up" list in https://github.com/Paratii-Video/paratii-portal/projects/1 for tracking stuff we _need_ to do.
