### ISSUE TITLE
Run etherum node in dev mode

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#20]
If we are going to be communicating w/ the blockchain in dev mode, we need to run an ethereum node concurrently with the dev server. Sounds like we will want to use `parity` instead of `testrpc`. 

We will need to point to this node in dev mode and point elsewhere in production.

**Comment by jellegerbrandy** [comment]
Yes, actually @geckoslair is now working on getting paratii-lib to work with parity - see https://github.com/Paratii-Video/paratii-lib/issues/26

This turns out to be more difficult then expected. 

In any case, this issue depends on the resolution of the paratii-lib issue.
