### ISSUE TITLE
embedding options

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#203]
This is from player 0.0.1: 

![image](https://user-images.githubusercontent.com/1306173/36347889-6f5a77a8-1463-11e8-92f8-ff46218932f2.png)

We should integrate similar options in the upload tool (or any place we show the iframe):

![image](https://user-images.githubusercontent.com/1306173/36347897-d913b43e-1463-11e8-88bd-5bc1b4086e3d.png)

**Comment by pedrocasa** [comment]
the solution for this inside the video frame (embed version) https://xd.adobe.com/view/61468153-87c9-4fdd-9caa-0c24d818c4e5
