### ISSUE TITLE
Add some text regarding the fact that we this is a beta, we welcome feedback, etc

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#206]

**Comment by jellegerbrandy** [comment]
@felipegaucho  can you write the text, and @pedrocasa can you decide where to show it?

**Comment by felipegaucho** [comment]
This is a *beta* tool! We ❤️ to get feedback on Telegram 🇧🇷 (t.me/paratiivideo| 🇺🇸(https://t.me/joinchat/EWZMBQ9mnqJ1--NKHpyF8A).

**Comment by pedrocasa** [comment]
Done in my design
#213
, waiting for @jrgarou changes
