### ISSUE TITLE
Autoplay broken

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#208]
Video stop go in autoplay..

**Comment by bent0b0x** [comment]
Can you provide some specifics/a gif?

**Comment by eliawk** [comment]
@bent0b0x sorry for the stupid issue, just to remember. on the br `upsert-video` when i go directly to the video link, i get the ipfsHash but the video doesn't start in autoplay.

**Comment by bent0b0x** [comment]
Gotcha, no problem. I've created many of these kinds of issues ;P.

Good to know!
