### ISSUE TITLE
Design.Portal UI & UX

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#213]
Here's the issue to talk about UI & UX
Last Update 11:56

https://xd.adobe.com/view/ac964a03-32b8-40ed-a868-4a849aecd855/screen/08089d32-4bc8-439d-9e61-761165c62d48/P-06

**Comment by felipegaucho** [comment]
@pedrocasa this was very mcuh conflicting with https://github.com/Paratii-Video/paratii-portal/issues/71

Closing this in favour of the other, definite thread, with the UI kit and its application to this first version of the portal.
