### ISSUE TITLE
fix "wallet" page you see when you click on the avatar

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#214]
It can be very simple in this first stage: just show the PTI balance (it has a bug now and shows 0) together with the address (i.e. `paratii.config.account.address`)

**Comment by bent0b0x** [comment]
We should look to reuse the `<PTIBalanceContainer />` at least for this first iteration

**Comment by pedrocasa** [comment]
Done in my design
https://github.com/Paratii-Video/paratii-portal/issues/213
, waiting for @jrgarou changes

**Comment by milankragujevic** [comment]
currently in the latest dev it shows PTI in text but shows the value in ETH, which can be verified by looking at the debug screen.

**Comment by jellegerbrandy** [comment]
so it does, good call Milan.

On Thu, Feb 22, 2018 at 10:19 PM, Milan Kragujević <notifications@github.com
