### ISSUE TITLE
Design.Portal Alerts & Notifications

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#238]
Issue to discuss which Alert/Notification element we should show to the user in this first version of the portal

It's important to know that we can use more than one solution to solve this problem. I only separated than because they are related to different elements. For example: Use the stable alerts and the form alerts

- Stable alert/notification boxes

! This solution may require an amount of time for the boxes disappear and don't be piled-up. 
The good point of using it: 1 - It's generic, can use for all kinds of dialog with the user
The bad point of using it: 1-  If we need to be very specific about a problem ( ie. if we need to warn the user that the description form has a problem) the user may get lost. 2 - the boxes may appear in front of some important information of the portal. We can add a close button to it but there's the possibility of  the user not closing it and not read what is needed 3 - If we need to alert the user about several problems ( ie. If he made a mistake with all 4 forms) the alerts will be piled up

![p_01 1](https://user-images.githubusercontent.com/30123644/36691025-d812888e-1b12-11e8-93c8-9bb573d61489.png)

- Forms alert

!This option needs to be performed along with another solution to work well
The good point of using it: 1- tells the user exactly where the problem is ( this is really important in a matter of UX) 
The bad point of using it: 1- It only refers to problems and notifications that are related to the forms. We will need another way of showing it to work together with it

![p_01 5](https://user-images.githubusercontent.com/30123644/36692187-2c71ae8e-1b16-11e8-8294-6d89638d6455.png)

- Mobile Alert boxes

!It may require a closing button on it
The good point of using it: 1 - tells the user exactly where the problem is 2- Can be used to a lot of different types of problems
The bad point of using it: 1 - Really complex to build/design 2 - Need to decide when it will disappear

![p_01 2](https://user-images.githubusercontent.com/30123644/36692410-c223fe82-1b16-11e8-8335-784b191fd648.png)

- Modals

The good point of it: 1- It's already built 2- It is the most explicit way to alert the user 
The bad point of it: 1 - The user can be bothered d by a modal appearing several times on his screen if we need to show it every time he does a regular action that needs a notification 2- The user must close it to other actions be available

![p_01 7](https://user-images.githubusercontent.com/30123644/36691797-0d200112-1b15-11e8-98a2-d3262de2808f.png)

**Comment by jellegerbrandy** [comment]
We can consider using this: https://github.com/gor181/react-notification-system-redux

**Comment by jellegerbrandy** [comment]
Here are some use cases to make the issue a bit more concrete:

* The user uploads a file, does not want to wait for the transcoder to finish, and starts watching a video. When the transocding has finished, he is alerted "Your video Xyz is now ready to play"
* A user clicks "submit' on the staking modal. When the action is successful, he is alerted "you have staked 5 PTI on video Xyz".  
* A user clicks "submit' on the save form. The action times out after 30 seconds because some service is not available. (Perhaps in the mean time the user may have navigated further?) He is alerted "Coud not save your data, connection to blabal timed out"
* The connection with the paratii-db is lost. "Cannot connect to db' (?)

**Comment by jellegerbrandy** [comment]
Personally, I'd be for the "stable alert"s in the first iteration.
I like the  mobile alerts as well (and they are probably not so hard to do once we have stable alerts), but we can look at that later.

**Comment by felipegaucho** [comment]
Closing this in favour of https://github.com/Paratii-Video/paratii-portal/issues/336
