### ISSUE TITLE
migrate features/player.test.js

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#25]
This  file contains the test from the meteor app https://github.com/Paratii-Video/paratii-player/ and describes the video player integration.

https://github.com/Paratii-Video/paratii-portal/blob/dev/features/player.test.js

The work to be done is to migrate these tests one by one, or decidign to delete the test if it is not relevant anymore. (The latter is the case for some tests that are now tested (or should be) in `paratii-mediaplayer`) and implement the corresponding functionality using `paratii-lib`.

**Comment by eliawk** [comment]
not all the test are working but i've removed all the useless and the misplaced ones

**Comment by eliawk** [comment]
@jellegerbrandy could we remove this generic issue?

**Comment by jellegerbrandy** [comment]
absolutely
