### ISSUE TITLE
Refactor Modal handling

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#268]
Currently, there is some state handlign for modals in `App.js`, which also contains logic for modals:

```
    this.state = {
      modalContent: false,
      showModal: false
    }

    this.showModal = this.showModal.bind(this)
    this.closeModal = this.closeModal.bind(this)
  }

  showModal (content: Object): void {
    this.setState({
      modalContent: content,
      showModal: true
    })
  }

```

This is incredibly difficult to use. instead of using the App asthe place where the state and the modal handlers live, we should use redux:

- the redux state should track the state of the modals
- showModal and closeModal will be reducers that chagne this state
- the modalcontainer will react to changes in the state

**Comment by bent0b0x** [comment]
Sounds great to me 👍 thanks for outlining this @jellegerbrandy

**Comment by jellegerbrandy** [comment]
Closing this as we pretty much have this
