### ISSUE TITLE
Find an alternative to Karma

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#274]
we use karma to run the unit test and it is **terrible**

we should try to use mocha

**Comment by bent0b0x** [comment]
What is terrible? FYI we are using mocha, but mocha is just the test framework. Karma is packaging and loading our tests in the browser

**Comment by jellegerbrandy** [comment]
:-)

I'm not sure about what the alternatives are, but this is terrible:
```
Chrome 64.0.3282 (Linux 0.0.0) Video Reducer TRANSCODING_PROGRESS should
update the transcoding status of the matching video in the store FAILED
AssertionError: expected { Object (123, 888, ...) } to deeply equal {
Object (123, 888, ...) }
    at Proxy.assertEqual (webpack-internal:///2384:1020:19)
    at Proxy.methodWrapper (webpack-internal:///2374:57:25)
    at Context.eval (webpack-internal:///2363:944:58)
```
The fact that i have to open a browser windwo, click on a button, click on
devtools, click on console, and then still do not have a good analysis of
the difference between the 2 objects, and need to inspect two different
object by hand, that is terrible.

As a question: why do these tests even _need_ a browser? We are just
testing a bunch of javascript functions here.

**Comment by bent0b0x** [comment]
Fair points.

I am pretty sure the assertion error message is actually written by `mocha`. `karma` does not deal w/ our assertions at this level.

I believe there is a newer version of `jasmine` that has very helpful messages for nested object differences.

Re: do we need a browser, we probably do not! All of our tests that require a browser should probably be handled by `chimp`. So I think we can revisit this option as well (however, the actual assertion messages will not be solved by this).

**Comment by jellegerbrandy** [comment]
This issue suggest that it is karma, not mocha, at the source of the
trouble.
https://github.com/karma-runner/karma-mocha/issues/76

(mocha gives very nice diffs of objects in our chimp-tests, so I don't
think mocha is at fault)

**Comment by bent0b0x** [comment]
Looks like it’s the fact that mocha is running in the browser; maybe we can use the config option highlighted here to fix:

https://github.com/karma-runner/karma-mocha/issues/76#issuecomment-201086393

**Comment by bent0b0x** [comment]
Regardless of this ☝️, though, I think running our unit tests on `node` is a good goal

**Comment by Leeaandrob** [comment]
https://github.com/facebook/jest

**Comment by jellegerbrandy** [comment]
@eliawk has so much improved the output of the test runner that I think we can close this
