### ISSUE TITLE
Loading bars actions

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#278]
Issue to discuss a possible resolution for the need to show the user what is the current status of the loading progress.

- The idea is to show the action that is happening using gray (#828282) color and after finished add a check icon and change the color for purple (#7D70FF)

the image below: upload has just finished but transcod**ing** process still in progress
![capture](https://user-images.githubusercontent.com/30123644/36804049-286a6ac8-1c98-11e8-9113-3296cd3485da.PNG)

**Comment by pedrocasa** [comment]
When it's 100% 

![capture](https://user-images.githubusercontent.com/30123644/36906315-5d5aafe0-1e14-11e8-8baf-81e41f3ca127.PNG)

**Comment by jellegerbrandy** [comment]
So this is the full list:

* Starting upload   (0%)
*  Uploading to IPFS (from 0 to 49%)
* [Upload (V)] Starting transcoder.. (50%)
* [Upload (V)] Transcoding... (50-99%)
* Ready to publish (V) (100%)

**Comment by jrgarou** [comment]
waiting on https://github.com/Paratii-Video/paratii-portal/pull/312
