### ISSUE TITLE
Paused video does not look like it is something that is a video

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#296]
We will get (at a certain point) preview images with a play icon, but for now we could just add an overlay here:

![image](https://user-images.githubusercontent.com/1306173/36910271-c31feec4-1e2f-11e8-9bf1-7afd3d17f0c1.png)

**Comment by felipegaucho** [comment]
This will be solved by https://github.com/Paratii-Video/paratii-portal/issues/449 !
