### ISSUE TITLE
Come up w/ plan for video controls on mobile

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#297]
When playing a video on mobile we see two sets of controls, the `iOS` native controls (when on `iPhone`) and our own controls. The two overlap.

We should probably just hide the native controls, but we should also evaluate how mobile-friendly our own controls are.

cc @felipegaucho @pedrocasa @jellegerbrandy

**Comment by jellegerbrandy** [comment]
Geckoslair @geckoslair (who is our expert in these matters) writes on gitter that:


> we need yo add playsline attribute to the video
> that's avoid ios to take control of the player

**Comment by jellegerbrandy** [comment]
What is the status of this issue?

**Comment by felipegaucho** [comment]
@geckoslair or @jellegerbrandy can we close this?
