### ISSUE TITLE
browser process will crash if you wait long enough

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#302]
From past experiments and related issues, we guess it has to do with ipfs overloading the local RAM.

**Comment by felipegaucho** [comment]
How should we proceed w/ this?
Discovering if its indeed the local RAM? Determining if there is a threshold (or an educated guess)?

**Comment by jellegerbrandy** [comment]
I have not seen this anymore - may have been fixed upstream in ipfs.
