### ISSUE TITLE
Popup warning for when uploader is leaving page

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#313]
*As suggested by early uploader Wesley Brasil*
Just to save people who inadvertedly click on "X" in the middle of an upload.

"**Do you really want to leave?**
There's some videos being sliced in the background.
**Go back**  |  **Exit**"

**Comment by jrgarou** [comment]
@felipegaucho @jellegerbrandy @pedrocasa 
the browsers [removed support for custom message](https://stackoverflow.com/questions/38879742/is-it-possible-to-display-a-custom-message-in-the-beforeunload-popup?answertab=active#tab-top)

We could call a [notification](https://github.com/Paratii-Video/paratii-portal/pull/311) after the user decide: 

![image](https://user-images.githubusercontent.com/320157/37037811-e394975e-2131-11e8-947d-b3be8890f65d.png)
![image](https://user-images.githubusercontent.com/320157/37037955-3a77c1ae-2132-11e8-8928-56a2411261a6.png)

**Comment by jrgarou** [comment]
@jellegerbrandy where should be the better place to check if there's some video being uploading?
Perhaps `components/App.js` because this behavior isn't only for `/upload`.
What do you think?

**Comment by bent0b0x** [comment]
@jrgarou yes this should be at the top level, so `App.js`.  However the component itself should not perform the check. There should be a new selector written in `UploaderSelectors.js` that contains the logic and then the resulting Boolean should be passed to `App.js` via `AppContainer.js`.

Let me know if you want me to explain further!
