### ISSUE TITLE
Create a docker machine for developers

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#316]
At the moment (as you can see in the readme), setting up a development environment involves installing portal as well ar paratii-db (which also includes settings up parity and mongodb) and starting up  all the services in the right order.

This is too complex and error prone. We hope to be able to simplify this process by using docker. In particular:

- we'd like is a docker machine such that a dev could just download the docker file, run `docker up` (or something similar), and have a portal instance running ready to test against
- devs need to be able to work with code on the host machine (i.e. edit the code, run git commands, etc). The right way here is probably to use a shared volume. 
- we should consider using `docker-compose` as well. 

So, very roughly, giving my limited knowledge of how docker works athis point, the process would work lke this:

* install docker and git on your machine
* `git clone` the paratii-portal docker image
* runing the docker image for the first time will `clone` the latest version of the various repositories
* `docker run -p 8080:8080 paratii-portal` will make the app avaiable on port 8080
* for development we could use shared directories, so we can continue using our dev tools locally. I.e. we can start docker like this:  `docker run --rm -it -v ~/dirgithubrepo_on_local_machine:/dirofgithubrepo_on_docker -p 8080:8080 paratii-portal`

**Comment by bent0b0x** [comment]
This would be awesome, hopefully we can get this up and running soonish 🙏
