### ISSUE TITLE
Mobile - focus on player has strange behaviour on mobile

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-portal#332]
Here's a behaviour of a video on the /embed route:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4333157/37174383-15422f5e-22f5-11e8-9247-e6db3b000fce.gif)

**Comment by geckoslair** [comment]
I think it's caused by the overlay that is blocking events propagations

**Comment by geckoslair** [comment]
same issue on telegram in-app player:

![photo_2018-03-08_17-46-51](https://user-images.githubusercontent.com/4333157/37175595-beaf951a-22f8-11e8-89c9-33b4b8dc0024.jpg)

**Comment by bent0b0x** [comment]
Resolved by #338
