### ISSUE TITLE
Design.Portal Uploader corrections 2#

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#334]
Some Issues related to the portal that needs to be fixed on the portal

- Resize the cards with the correct value of each breakpoint
- There's only four sizes of fonts in this design (text-small,text-main,title-small,title-main).
- It's important to know that those sizes decrease proportionally as the breakpoints get smaller
- Remove the graphics background of the "video-list card" and the "edit-video card".
- Resize the header and the footer with the new values. Both of them are 72px height (I think Elia has already fixed the header size).
- Try to approximate the distance value between the cards&header&footer and the distance between card&card for what we have on Adobe specs
- "text-small" should be 0.85 rem not 0.8
- The beta warning of the footer should be centralized with the page
- Change the height of the PTI guide illustration for 130px
- Change the height of the upload illustration for 110px
- Change the height of the voucher illustration for 140px
- Change the Paratii logo on the "loading thumbnail" for only the Paratii symbol
- The order of the elements in the edit page is wrong when the screen size is less than 1024px ( the buttons should be the last elements of the card and should be under the loading bar)
- Remove the URL address when the video is not published yet
- When the video is already published we can hide the loading bar and show under the title header that the is already published ( something like " published in July of 2018"
- When the video is already published we can change the word "save" on the save button for "save changes" (it will appear disabled if the user didn't change anything on the input fields)

**Comment by jrgarou** [comment]
@pedrocasa

> Resize the cards with the correct value of each breakpoint

In fact, a lot of this implementations was done. I just need to fix some breakpoints to `1024`. I'll review everything again.

> There's only four sizes of fonts in this design (text-small,text-main,title-small,title-main).
It's important to know that those sizes decrease proportionally as the breakpoints get smaller
> "text-small" should be 0.85 rem not 0.8

Could you send those values together?

>Remove the graphics background of the "video-list card" and the "edit-video card".

Done https://github.com/Paratii-Video/paratii-portal/commit/e5629ca42f05c2341072e1d447a083a4dd9d0b0c

> Resize the header and the footer with the new values. Both of them are 72px height (I think Elia has already fixed the header size).

Done https://github.com/Paratii-Video/paratii-portal/pull/324

> Try to approximate the distance value between the cards&header&footer and the distance between card&card for what we have on Adobe specs

Done https://github.com/Paratii-Video/paratii-portal/pull/324

> The beta warning of the footer should be centralized with the page

It's very strange to align an item to the left and another centralized. Looks like something is missing on right or the content(both texts) should be aligned on center.
![image](https://user-images.githubusercontent.com/320157/37213870-10cb2640-2392-11e8-919b-9e19ef521988.png)

> Change the height of the PTI guide illustration for 130px
Change the height of the upload illustration for 110px
Change the height of the voucher illustration for 140px

Done https://github.com/Paratii-Video/paratii-portal/commit/c4382d2cb4f247a1b348a06ee301c7c5bf9883e7

> The order of the elements in the edit page is wrong when the screen size is less than 1024px ( the buttons should be the last elements of the card and should be under the loading bar)

I think this is fine. The button should be next to its form to avoid the scroll just for saving the data.


> Remove the URL address when the video is not published yet
> When the video is already published we can hide the loading bar and show under the title header that the is already published ( something like " published in July of 2018"
> When the video is already published we can change the word "save" on the save button for "save changes" (it will appear disabled if the user didn't change anything on the input fields)

Need to implement

**Comment by jrgarou** [comment]
> Change the Paratii logo on the "loading thumbnail" for only the Paratii symbol

@pedrocasa I'm using this image https://paratii.video/public/images/paratii-src.png
Could you send the correct image?

**Comment by jellegerbrandy** [comment]
What is the status of this, @pedrocasa ?

**Comment by pedrocasa** [comment]
@jellegerbrandy Most of them are already done. and the ones that we couldn't handle were solved in the new version of the uploader page  Paratii-Video/paratii-portal#71
