### ISSUE TITLE
Video not found stop working

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#335]
The not found page has stopped working if the video doesn't exist. 
After the `fecthVideo` call the there is 
`const fetchStatus = nextVideo.getIn(['fetchStatus', 'name'])`

It seems it doesn't enter in `componentWillReceiveProps`

**Comment by eliawk** [comment]
@bent0b0x i thought that render the `404` instead of redirect it's more clear. It means that particular content can't be found, but this is just my point.

**Comment by bent0b0x** [comment]
The message in the 404 component does not make sense for the video page. Maybe we can have a generic 404 page that we redirect to but when we go to a video page that doesn't exist show a different message.

The 404 message is something like "someone is working on building this but it doesn't exist yet". We should just say "A video w/ that id does not exist" or something.

cc @pedrocasa

**Comment by jellegerbrandy** [comment]
Just to be clear: The 404 http status code has a fairly precise menaning, it  just means "Not found", and no more.  It does _not_ mean "someone is working on it".

It is the right http response to use when we do not having found a requested video, so we wil continue to send that. 

In particular, this implies that we should _not_ do a redirect (which means send a 301 or similar, which is just the wrong answer and will confuse both crawlers and users)

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

We can send anything we want in the body of the resonse,  though, and I agree with ben we could do something more specific than "this is a 404 error"  - a message like "We could not find a video with this id" would  be nicer.

**Comment by jellegerbrandy** [comment]
this is broken at the moment.

I see a player (but no video) here: https://staging.paratii.video/play/ThisDoesNotExist

We need to fix this asap, but this tim there should also be a woring test that would hve caught this bug.
