### ISSUE TITLE
Implement missing alerts/notifications

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#336]
### Uploading
- [x] title: 'Be Patient!'  // message: 'We are working on your file.'
- [x] title: 'Upload Error' // message: 'Something went wrong with your file. May you retry?'
- [x] title: 'Local upload' // message: 'The local upload has been done.'
- [x] title: 'File uploaded' // message: 'Now we need to transcode your pixels.'
- [x] title: 'Transcoder Error' // message: 'The machines are not cooperating. Can you refresh?'
- [x] title: 'Transcoding' // message: 'The transcoding has started.'
- [x] title: 'Transcoding done' // message: 'You video is ready to be published!'
- [x] title: 'We are saving your data.'
- [x] title: 'Data saved!'

### Voucher redeeming:
- [x]  title: 'Reading...'
- [x]  title: 'Success' // message: 'You have earned X PTI.'
- [x]  title: 'Ooops!' // message: 'This voucher doesn't exist.'
- [x]  title: 'Oh, no!' // message: 'This voucher was already used.'

### Staking:
- [x]  title: ''Processing..."
- [x]  title: 'Stake well-done' // message: 'You have staked X PTI.'  **[let's not show towards which video, here]**
- [x]  title: 'Not enough tokens' // message: 'You need at least 5 PTIs to make a stake.'
- [ ]  title: 'Ooops!' // message: 'This voucher doesn't exist.'

### Random:
- [ ] title: 'Connection timed out' // message: 'Please refresh the page.'

**Comment by eliawk** [comment]
@felipegaucho 
Staking: `Ooops!' // message: 'This voucher doesn't exist.'` i think it's related to redeemvoucher flow and modal

Random: title: 'Connection timed out' // message: 'Please refresh the page.' - atm we don't have any system to check it and so to show the notification

**Comment by felipegaucho** [comment]
Agreed 👍👊
