### ISSUE TITLE
limit the upload to 300MB

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#341]
It is already in paratii-lib with this PR: https://github.com/Paratii-Video/paratii-lib/pull/160#event-1517067915

We just need so show somethign to the user here. Maybe a generic error  notification, @eliawk, so we can do this quickly?

**Comment by ya7ya** [comment]
@jellegerbrandy it already does show the error.. so i think we should be fine :) 
![err](https://user-images.githubusercontent.com/932163/37314309-0c8f4134-265c-11e8-8ee5-24596d758aa5.jpg)

**Comment by jellegerbrandy** [comment]
These are the best kind of fixes :-)
