### ISSUE TITLE
Implement stats box 

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#353]
We want to make available some basic p2p stats for users, on the embedded player. These can be either inside the wallet/profile space, or separate. I suggest we show:

X Peers
Y Mb stored || (amount of localStorage we're using [under the suggestion of @eusourye, an early uploader]).
A cellphone-battery-level-like meter for showing the speed of upload and download (I don't think users will care for individual speeds, but a general visualisation of connection quality can be nice to have. We can have 4 levels of quality according to our averages).
It'd be great to have this almost as a warning, until the user clicks it for the first time (the fact we're using the user's storage should be transparent just like sites are when telling users they have cookies).

- [ ] Design (we had something like this for the legacy player)
- [ ] Implement

**Comment by felipegaucho** [comment]
@pedrocasa also a design we could resurface, in your free time ☝

**Comment by jellegerbrandy** [comment]
Here's an example from our friend flavio: https://github.com/flavioribeiro/clappr-p2phls-stats-plugin
