### ISSUE TITLE
Sharing overlay opacity settings (make more transparent)

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#359]
A minimal thing. The "sharing" overlay is 100% opaque as of today:

<img width="969" alt="screen shot 2018-03-15 at 11 53 16 am" src="https://user-images.githubusercontent.com/26517120/37482628-79e04da6-2863-11e8-8016-61df4f367168.png">

References are not 100% opaque, usually there's some transparency to see the video behind (we were like this, until some days ago):

<img width="436" alt="screen shot 2018-03-15 at 3 14 52 pm" src="https://user-images.githubusercontent.com/26517120/37482786-ea5d368e-2863-11e8-9a0b-9c41d169182e.png">

@pedrocasa do we have specs on this?

**Comment by jellegerbrandy** [comment]
It is still completely opaque in production, @jrgarou

**Comment by jellegerbrandy** [comment]
apologies. The problem was #392
