### ISSUE TITLE
Progress bar on player never disappears

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#360]
Even when the mouse goes away, it remains there, on the bottom. No controls should remain once the video is playing or buffering and the 'mouse' is away,

![giphy 9](https://user-images.githubusercontent.com/26517120/37483448-cced4e8a-2864-11e8-8615-be66fb85bd37.gif)

**Comment by jrgarou** [comment]
Looks fine to me

**Comment by jellegerbrandy** [comment]
yeah, sorry, looks fine to me as well. I had checked prodcution but there was an issue with thecontinuous deployment so it was an old version.
