### ISSUE TITLE
Voucher code succeeds, notifications say I'm good - but 0 PTIs in the wallet!

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#366]
It all goes right, but the counter remains at "0".

![giphy 10](https://user-images.githubusercontent.com/26517120/37547118-8e556db6-294e-11e8-81a6-f80cc3401f17.gif)

**NOTE: When I refresh the page, the missing PTI are miraculously there.**

**Comment by bent0b0x** [comment]
@felipegaucho let me take a look at this, the fix should be simple

**Comment by bent0b0x** [comment]
And as an FYI, we have basic repetitive polling logic that refreshes the balance every 3 minutes (it used to be like every 5 seconds). Maybe we can find a happy medium.

For this issue, though, I will refresh the balance once staking is successful

**Comment by felipegaucho** [comment]
> And as an FYI, we have basic repetitive polling logic that refreshes the balance every 3 minutes (it used to be like every 5 seconds). Maybe we can find a happy medium.

That might be it. I'm sure @jellegerbrandy and the guys are in favour of as minimum polling as possible, but now I published a video, made a stake, and the balance didn't update until I noticed much later. Can we refresh it once a stake is made, too?

**Comment by bent0b0x** [comment]
@felipegaucho we certainly can. Obviously this kind of solution is not sustainable so we need to come up w/ a plan to either poll or maintain a socket connection to always live update this value. 

Before I implement this, are there other functionalities in our portal right now that you can think of that update your PTI balance?

**Comment by felipegaucho** [comment]
As we spoke today, so far just redeem voucher and publish+stake. Happy to close this issue once https://github.com/Paratii-Video/paratii-portal/pull/370 is working fine

**Comment by bent0b0x** [comment]
@felipegaucho sounds good. I just merged that PR but we can leave this open until it is in Production
