### ISSUE TITLE
Scrollbars in chrome are UGLY

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#372]
![image](https://user-images.githubusercontent.com/1306173/37604954-addcc4d8-2b81-11e8-821b-0cd262ff0ebb.png)

**Comment by jellegerbrandy** [comment]
Similar on the picker:
![image](https://user-images.githubusercontent.com/1306173/37605043-e07e352a-2b81-11e8-8ddc-e96440b6d668.png)

**Comment by bent0b0x** [comment]
I will dig into this more in depth later, but as far as I can remember this is not something we can control. I believe this is specific to the browser. The scroll bars in my chrome do not look like that, FYI. They look far more natural.

I'll investigate though.

**Comment by bent0b0x** [comment]
I'll investigate this further, but FYI the scroll bars do _not_ appear that way on my machine on Chrome. @jellegerbrandy what version of Chrome are you running in that screenshot?

**Comment by jellegerbrandy** [comment]
Version 64.0.3282.140 (Official Build) (64-bit)
Also Enrico has it.
Perhaps a mac thing?
I'm not sure about the scrollbars in any case. They seem unecessary in the quality control, where the "scrolling" is only half a character height. Or do I mistunderstand something?

**Comment by bent0b0x** [comment]
These should not be showing up as native scrollbars as you see them, and I never saw those in development.

This problem seems sort of familiar, but from what I remember it was a browser setting that causes them to appear this way, and causes them to appear when they aren't supposed to. I'll have to dig into it more later.

**Comment by jellegerbrandy** [comment]
Issue is still there: 
![image](https://user-images.githubusercontent.com/1306173/37660214-6bc57426-2c41-11e8-983d-598d547110fa.png)
