### ISSUE TITLE
Adapt progress and volume scrubbers to match design

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#378]
As seen [here](https://xd.adobe.com/spec/4b1b6f6b-81c7-461c-9491-e738a3c5294b/#screen/9dcfd0d2-002f-4378-ba55-fd0aee1d065e/volume-bar%20-%20option1), the scrubbers for progress and volume should have a slightly transparent outer circle.

![image](https://user-images.githubusercontent.com/7697924/37631535-84f68ba0-2bc0-11e8-847f-6a72f60dcebc.png)

Currently, they are fully opaque and should be updated.

![image](https://user-images.githubusercontent.com/7697924/37631552-90dba1a8-2bc0-11e8-8289-a8fddd7c1de5.png)

**Comment by bent0b0x** [comment]
@pedrocasa could you please attach an svg for the scrubber when you have time? 😄 

As discussed on `gitter`, it is possible to build this scrubber w/ just css but it will be much more consistently rendered if delivered as an svg.

**Comment by pedrocasa** [comment]
here it is https://we.tl/KWZxMVjEK5

**Comment by bent0b0x** [comment]
@jrgarou I think we can close this, do you agree?

**Comment by jrgarou** [comment]
@bent0b0x I think so, but @pedrocasa could review this before we close this issue

**Comment by bent0b0x** [comment]
@pedrocasa what are your thoughts?

**Comment by felipegaucho** [comment]
@pedrocasa , closing for you! Feel free to reopen if not there yet.
