### ISSUE TITLE
message after adding voucher is wrong and balance does nto update

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#385]
It says "you have earned true PTI" and it does not immediatly update the balacne.

**Comment by eliawk** [comment]
on `paratii.lib` i've changed the function to return the amount:
```
let amount = getInfoFromLogs(tx, 'LogRedeemVoucher', '_amount', 1)
      if (claimant === this.eth.config.account.address) {
        return amount
      }
```

don't know why still return `true`

**Comment by jellegerbrandy** [comment]
Ok, it does return an amount now.

It is in WEI, though, and needs to be converted in the message.

**Comment by felipegaucho** [comment]
Still needs to be converted from WEI,

<img width="788" alt="screen shot 2018-04-13 at 3 58 45 am" src="https://user-images.githubusercontent.com/26517120/38721063-1ac32366-3ecf-11e8-8618-58e86ed94569.png">

The "Oh no" message is lovely, though :)

<img width="554" alt="screen shot 2018-04-13 at 3 58 57 am" src="https://user-images.githubusercontent.com/26517120/38721078-246d65de-3ecf-11e8-8c37-1fe30b120fc8.png">

**Comment by eliawk** [comment]
this has been fixed here https://github.com/Paratii-Video/paratii-portal/commits/fix/385-redeem
