### ISSUE TITLE
message "you have staked 5PTI" needs a space between "5" and "PTI 

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#386]

**Comment by felipegaucho** [comment]
Also, don't know if @jrgarou caught it, but the notification is showing me the value in smaller units, I assume. Got one for a voucher giving me 230000000000... PTI.

**Comment by jrgarou** [comment]
Done on https://github.com/Paratii-Video/paratii-portal/pull/394
