### ISSUE TITLE
[Blocking Twitter] page header says "Video Not Found" instead of the title of the video

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#399]
![image](https://user-images.githubusercontent.com/1306173/37899218-2d93ec42-30eb-11e8-8598-215b72282785.png)

**Comment by geckoslair** [comment]
can you send me a link that breaks metadata and/or twitter?
@jellegerbrandy @felipegaucho

**Comment by geckoslair** [comment]
after debugging...
twitter issue and this are two different issues:

1. Twitter: my fault, pushed in dev and master in order to fix
2. Seems a wrong ENV settings in portal server that brokes meta info on staging

**Comment by geckoslair** [comment]
I'll close this, i've created a new issue for ENV settings
https://github.com/Paratii-Video/paratii-portal/issues/403

Enrico.
