### ISSUE TITLE
Remove thin line from video quality plugin

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#401]
![image](https://user-images.githubusercontent.com/7697924/37917977-ce378882-30ed-11e8-82d0-63cec599808a.png)

**Comment by bent0b0x** [comment]
Related to [paratii-mediaplayer#47](https://github.com/Paratii-Video/paratii-mediaplayer/issues/47)

**Comment by jrgarou** [comment]
@pedrocasa @bent0b0x there more details about the **thin line from video quality plugin**?

**Comment by bent0b0x** [comment]
@pedrocasa please verify but I believe this is already fixed on production and we can close. 

@jrgarou basically there used to be a thin white border between the plugin header (“Video quality”) and the list of qualities to choose from.
