### ISSUE TITLE
Pass configuration to the application

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#41]
At the moment, the `provider` and the user's addresses are hardcoded in  `scripts/utils/ParatiiLib.js`.

This will not do, of course: our test wil use different settings then the production app (i.e. the bundle that is created for distributing)

We need some way of passing in such configuration in the application, so that we can do things like:

    $ startapp --config configfile.js

Or 

    $ webpack --config configfile.js

(Confession: I have no idea how  to pass config to these tools)

**Comment by eliawk** [comment]
this is related to #51

**Comment by jellegerbrandy** [comment]
Closing this in favor of #51. High priority, this one!
