### ISSUE TITLE
Portal title is not dynamic

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#410]
**Problem**
- Navigate to the home page of the portal
- Then, click to play a video

The title of the page remains `Paratii`.

Alternatively:
- reload the browser with a `play/:video_id`
- then click to navigate to the uploader

The title of the page remains as the title of the video you were playing.

The titles of our pages should be deterministic regardless of the path you take to get to a particular url.

cc @geckoslair

**Comment by geckoslair** [comment]
@bent0b0x 
what you think about this two solutions:

1. https://github.com/nfl/react-helmet -> manage both routing (client and server)
2. Just refresh metadata client side during route change.

**Comment by bent0b0x** [comment]
@geckoslair React helmet looks pretty cool. If it works such that we can specify a `title` in the play component only and no other `head` elements will be affected, then I think we should definitely do it.

**Comment by bent0b0x** [comment]
This is fixed
