### ISSUE TITLE
Investigate moving back to yarn

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#42]
We had to switch to `npm` via #38 , because of issues installing certain dependencies (I think it was web3?) with `yarn`. However, I was on a very old version of `yarn` that may have explained the trouble. Will investigate if we can switch back.

**Comment by bent0b0x** [comment]
Someone else feel free to try, but this is not working for me, but with different issues from before.

Basically, `yarn` seems to refuse to install `tar.gz`. After `yarn` it is never present in `node_modules`. Even if you do `yarn && `yarn add tar.gz`. You end up w/ this warning:

```
warning Pattern ["tar.gz@^1.0.7"] is trying to unpack in the same destination "/Users/benjaminbaum/Library/Caches/Yarn/v1/npm-tar.gz-1.0.7-577ef2c595faaa73452ef0415fed41113212257b" as pattern ["tar.gz@^1.0.5"]. This could result in a non deterministic behavior, skipping.
```

This package is deprecated, but it should still install. I think it is related to this [yarn issue#4812](https://github.com/yarnpkg/yarn/issues/4812).

**Comment by bent0b0x** [comment]
Should reinvestigate

**Comment by jellegerbrandy** [comment]
I am using yarn without problems. @bent0b0x , you still have problems? The `package.json` commands use yarn.

If no-one reports problems, we should update the README and the circleci tests as well to reflect that we are using `yarn`.

**Comment by Leeaandrob** [comment]
I am using yarn only to build `yarn build` on stage and production environment. @bent0b0x

**Comment by bent0b0x** [comment]
FYI the question w/ `yarn` is not whether we can use it to run our build scripts, but rather whether we can use it to install our dependencies. Looking into this now!

**Comment by felipegaucho** [comment]
Closing this, please undo if still relevant.
