### ISSUE TITLE
Transparence on the player lower bar

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#420]
As discussed w/ @pedrocasa, let's take out the opacity (makes it heavy) and use transparency w/ shade, as its practiced in other players.

**Comment by pedrocasa** [comment]
Changes have been already made on the design wiki

**Comment by jrgarou** [comment]
@pedrocasa  https://xd.adobe.com/spec/7f9e0d73-b3e7-43fc-bff2-c48187bef63f/
Is this the correct file?
How to download it?

**Comment by pedrocasa** [comment]
Yes it's.
it's on our dropbox.
