### ISSUE TITLE
Quality control on the player -> cleanup

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#421]
<img width="246" alt="screen shot 2018-04-02 at 2 19 39 pm" src="https://user-images.githubusercontent.com/26517120/38206484-ee551c5e-3680-11e8-8012-90db204265c3.png">

- [x] Video quality -> Quality
- [x] kbps, or px -> p (simply p, as in `1080p`)
- [x] Automatic -> Auto.
- [x] Scrollbar on Mac -> @jrgarou plz help us kill it, @bent0b0x can't test it since he has no Mac, we can even hide some resolutions in order to avoid the pop up from becoming too long vertically.

**Comment by jrgarou** [comment]
- [ ] Remove scrollbar on `/embed

![quality-modal-generates-a-scroll](https://user-images.githubusercontent.com/320157/38211779-f6b5371a-3691-11e8-96a7-bd2f04d8bab7.gif)

**Comment by felipegaucho** [comment]
@jrgarou, in case it's still not clear: we do not want the scroll bar to be there. It is a bug. We need you to help take it away. We should never have more resolutions than what fits inside the box.

🇧🇷 Nunca devemos ter mais resoluções do que cabe na caixa - não queremos a scroll bar jamais, nunca, em nenhum lugar dentro do player.

**Comment by jrgarou** [comment]
@felipegaucho it's clear 👍
My comment is just another fix for the "Quality control".

**Comment by ya7ya** [comment]
hey , regarding the video qualities , here are the `MAX_BIT_RATES` i use in our transcoder. note that this isn't an exact science, and these values could change.

```javascript
const MAX_BIT_RATE = {
  '1080': '2760700',
  '720': '1327100',
  '480': '763900',
  '360': '423900',
  '240': '155600',
  '144': '64000'
}
```

**Comment by bent0b0x** [comment]
Can we close this @felipegaucho @jrgarou ?

**Comment by jrgarou** [comment]
it's ok to me

**Comment by felipegaucho** [comment]
Superb @jrgarou 👏
