### ISSUE TITLE
Video title is disproportionally big on Twitter

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#422]
<img width="1280" alt="screen shot 2018-04-02 at 2 04 17 pm" src="https://user-images.githubusercontent.com/26517120/38206517-0e9aa7f4-3681-11e8-8e5e-cd1f663e749d.png">

@pedrocasa, right (specially in comparison w/ all icons)? @geckoslair should you be able to correct it your side?

**Comment by bent0b0x** [comment]
Not sure @geckoslair should be responsible for this. Either I or @jrgarou can take this one once we have a good idea from @pedrocasa of how we should scale it down

**Comment by jrgarou** [comment]
@felipegaucho @bent0b0x I send a file to @pedrocasa  to create rules from our typography.
Basically is create 3 classes for titles and texts e make the adjusts on it.
With that, we don't need to care about typography - maybe just in some cases like buttons, form elements, etc.


```
   .title-big {
      font-size: 2rem;
      font-weight: 400;
      line-height: 1.7;
     
      @media (max-width: 1024px) { // example of the tablet
           font-size: 1.75rem;
           line-height: 1.6;
      }
     
      @media (max-width: 768px) { // example of the phablet
           font-size: 1.75rem;
           line-height: 1.6;
      }
    }
    .title-main {
      font-size: 1.75rem;
      font-weight: 400;
      line-height: 1.6;
    }
    .title-small {
      font-size: 1.5rem;
      font-weight: 400;
      line-height: 1.6;
    }
    .text-big {
      font-size: 1.1rem;
      font-weight: 400;
      line-height: 1.5;
    }
    .text-main {
      font-size: 1rem;
      font-weight: 400;
      line-height: 1.75;
    }
    .text-small {
      font-size: 0.8rem;
      font-weight: 400;
      line-height: 1.88;
    }
    .text-tiny {
      font-size: 0.7rem;
      line-height: 1.7;
    }
```

**Comment by felipegaucho** [comment]
@jellegerbrandy , this was supposedly fixed (along w/ the wallet and resolution oversized popups) a couple days ago by a @jrgarou PR that got merged into dev, can we check?

**Comment by jellegerbrandy** [comment]
yeah, staging is broken at the moment, waiting for yahya to fix it, then we
can move it up the pipeline to production
