### ISSUE TITLE
🌊Player v0.0.2 RELEASE 🚀

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#423]
> 🌊 The second iteration of Paratii's player - sleeker, lighter and faster, marking the migration away from Meteor and towards Clappr/React. To be shared extensively on Twitter. Still under heavy development. ⚡

# 🌍 What's left to release

- [x] Transparence on the lower bar @pedrocasa https://github.com/Paratii-Video/paratii-portal/issues/420
- [x] Rebuild the video title on the embeded player
- [x] Quality control cleanup https://github.com/Paratii-Video/paratii-portal/issues/421

_Doesn't block the release but would be cool to have_:
- [x] Integrate player.js and 
- [x] get approved on embed.ly submission
- [x] Tests (@bent0b0x please elaborate)

# 🔦 Highlights

### New functionality!
**Design**. The player is prettier, its icon set is cohesive and broad, signature details are the colours and 'surprise' features like the wallet.
**Integration**. Twitter, Telegram, Whatsapp, Android, iOS.  They all have their quirks and conditions, and we are trying to accommodate all. Others still to come!
**Video quality selector**. The player will automatically select the best download speed for your conditions, but if you don't agree, now you can choose the resolution yourself.

### A way for you to upload
A select batch of "early uploaders" have been testing https://github.com/Paratii-Video/paratii-portal, which we're building as an easy way to onboard content on the decentralised web. Another batch is opening soon, before the system is publicly opened. It's much nicer to share the player around when there's fresh content to display ;)

### Slim wallet
Differently than thew prototype we released last December, v0.0.2 has a slim wallet, that won't bother those unwilling to mess with it. The player is lighter, more familiar, and caters better to publishers willing to experiment with p2p video distribution on their pages.

# 📏 Optimization

The main download has been reduced from >6M to 887Kb (and is being reduced further), which makes the player load much faster. Video delivery has become smoother with upgrades to new versions of the ipfs-js and libp2p protocols, so the average buffer time has fallen too. Transcoding average speed (not benchmarked previously) is at ~**1:1 for anything less than 720p**, and around **~1:1.2 for 720p and 1080p**. Finally, there's a new stream-multiplexer in town, so multiple streams can be used as a single one, and we're starting to test IPFS relays, which should make it easier for peers to find each other.

# ✅ Release Checklist

- **Robustness and quality**
  - [ ] Ensure that all tests are passing.
- **Documentation**
  - [ ] Ensure that README.md is up to date
  - [ ] Review embedding documentation (is up to date @geckoslair ?)
  - [x] Create the release issue
- **Communication**
   - [ ] Medium post (showcasing the 7 videos we've been promoting on twitter too - would be awesome to have them embedded @enricocicconi)
   - [ ] Twitter
   - [ ] Telegram
   - [ ] Reddit
   - [ ] Facebook

# 🙌🏽 Want to contribute?
Please first have a quick look at our contribution guidelines [here](https://github.com/Paratii-Video/wiki/blob/master/CONTRIBUTING.md). Be on the lookout for issues labeled with something that catches your eyes and sparks your interest. And feel free to drop a line on [gitter](https://gitter.im/Paratii-Video) about anything relevant to the issue - from a UX suggestion to a bug fix.

**Comment by bent0b0x** [comment]
I'll elaborate on tests:

It is not _necessary_ to release, but we really do need to improve our tests. Specifically our tests that launch a browser, visit a video url and manipulate the controls/player and ensure it is working. This will be crucial as we move forward to ensure we don't break the player again :). 

I plan on improving our testing quantity and quality, with regards to the player specifically, this week.

**Comment by jellegerbrandy** [comment]
* I added point about design (perhaps we can say more than just "prettier" :-)), resolution pciker, and integration.  and optimization
* @geckoslair : can you perhaps elaborate on the embedding side?
* @ya7ya , if there is more specific things to say about ipfs/playback stuff, can you check?
* what @bent0b0x says about testing
* the real benchmark would be "time-to-play" (i.e. time between clciking on the link and video starts playing). We do not have numbers for that (it is hard to collect, Mux would be perfect for this ...).

**Comment by ya7ya** [comment]
> Transcoding average speed (1 : 1 for 4 downsamples, right @ya7ya?)

1:1 for anything less than 720p, and around 1:1.2 for 720p and 1080p.

> @ya7ya , if there is more specific things to say about ipfs/playback stuff, can you check?

well, on the technical IPFS side. we're starting to test ipfs relays which should make it easier for peers to find each other. and that should help overall performance.  there is also a new stream-multiplexer in town. so multiple streams can be used as a single one.

thats pretty much it. 😄

**Comment by felipegaucho** [comment]
👏 guys 👊
