### ISSUE TITLE
Rebuild the video title on the embeded player

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#432]
Correct the typography size of the embeddable videos. (Sizes valus are in the Adobe XD dropbox and on the Adobe specs of the player UI-kit.)
Also, we show consider put three small dots if the entire title of the video doesn't fit inside the iframe

**Comment by jrgarou** [comment]
@pedrocasa I can't open those files on Adobe XD.

<img width="350" alt="screen shot 2018-04-05 at 19 24 23" src="https://user-images.githubusercontent.com/320157/38394961-fcc476f8-3906-11e8-8ff5-2eaf6b02a7cf.png">

**Comment by bent0b0x** [comment]
Can we close this one?

**Comment by jrgarou** [comment]
@pedrocasa could you check this?
