### ISSUE TITLE
Reminder - upgrading to the new lib with fixed address generation

### ISSUE THREAD

**Issue by LorenzoAlluminio** [Paratii-Video/paratii-portal#433]
Now the pinned version when using portal is the old lib with the wrong address generation with this development.json

`{
  "provider": "http://localhost:8545",
  "address": "0x9e2d04eef5b16CFfB4328Ddd027B55736407B275",
  "privateKey": "399b141d0cc2b863b2f514ffe53edc6afc9416d5899da4d9bd2350074c38f1c6",
  "db.provider": "http://localhost:3000"
}`

when using the upgraded lib it should become
`{
  "provider": "http://localhost:8545",
  "address": "0xCbe4f07b343171ac37055B25a5266f48f6945b7d",
  "privateKey": "0x399b141d0cc2b863b2f514ffe53edc6afc9416d5899da4d9bd2350074c38f1c6",
  "db.provider": "http://localhost:3000"
}`

**Comment by bent0b0x** [comment]
@LorenzoAlluminio should we do this now? I am experience issues developing locally

**Comment by LorenzoAlluminio** [comment]
It depends on which version of the lib you are using.
If you are using the new lib with the correct address generation, then yes.

I didn't do it because the pinned version was still the old one

**Comment by jellegerbrandy** [comment]
this is now ok on dev (I think)
