### ISSUE TITLE
pin screen: shall we remove the "continue" button?

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#443]
I.e. we can submit the form immediatly, without bothering the user with a "continue" click

**Comment by eliawk** [comment]
@pedrocasa what do you think about this?

- w/out the button the process is quicker but maybe is too automatic for the user
- the button make design coherence in all the modal (go back / continue)
- i agree w/ @jellegerbrandy the continue in this case could be bothering for the user

**Comment by jellegerbrandy** [comment]
+1 for removing (but let's not get stcuk on this, it is not that important)

**Comment by felipegaucho** [comment]
+1 for removing too

**Comment by eliawk** [comment]
ok, just wait a confirmation from @pedrocasa too.

**Comment by jellegerbrandy** [comment]
guys, we have decided to use a text password now, right? 
So this discussion is not relevant anymore, closing the issue
