### ISSUE TITLE
when giving the wrong pin on the secured account, we should ask again

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#445]
We can add an option: "Don't remember you pin? You can create a new account"

**Comment by eliawk** [comment]
@jellegerbrandy you mean in the pin check step?

<img width="519" alt="schermata 2018-04-10 alle 10 00 05" src="https://user-images.githubusercontent.com/362016/38543836-fcb29472-3ca5-11e8-80fb-cd45739ea2b0.png">

**Comment by jellegerbrandy** [comment]
I meant in the "reload after you secured your account" situation. If yu give the wrog pin, it says "wrong pin" and then just shows the page. It should say "sorry, wrong pin, please try again", show the pin page, and give an extra option "don't remember your pin? - you can create a new account or restore yuor account fromt he 12 word phrase".

**Comment by eliawk** [comment]
@jellegerbrandy ok got it
