### ISSUE TITLE
Quality controls are using wrong font size when it is in fullscreen mode

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#448]
The right font size of the quality control for video frames that are bigger than 1440  is text big.
All values can be found on the Adobe specs on design (https://github.com/Paratii-Video/paratii-portal/wiki/Design-Wiki)  wiki and on the master folder of paratii dropbox (https://www.dropbox.com/home/paratii-design/master)

**Comment by felipegaucho** [comment]
Duplicate issue.
