### ISSUE TITLE
Correct layout of the quality card/wallet card if it doesn't fit on the video frame 

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#450]
The  quality card should be like this if it doesn't fit on the video frame 

File on the adobe specs  (https://github.com/Paratii-Video/paratii-portal/wiki/Design-Wiki) and dropbox folder https://www.dropbox.com/home/paratii-design/master

![iphone 6-7-8 1](https://user-images.githubusercontent.com/30123644/38525335-3d9bc48c-3c28-11e8-9c6e-f44e79b91996.png)

The wallet card should be like this if it doesn't fit on the video frame

![screen shot 2018-04-09 at 7 15 08 pm](https://user-images.githubusercontent.com/30123644/38526191-acabf4fc-3c2b-11e8-8e66-c842ce29188c.png)

**Comment by felipegaucho** [comment]
In theory solved by the same PR that solved https://github.com/Paratii-Video/paratii-portal/issues/432
