### ISSUE TITLE
Do not allow users to select video file types that we do not support

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#452]
Right now the user can select any video file (and maybe even images?) to upload. However, if they select something other than an `.mp4` the upload works but transcoding will hang forever and then nothing happens.

We can restrict on the client the type of files the user can select.

@pedrocasa @felipegaucho thoughts on adding some verbiage in the uploader to tell the user about this restriction?

**Comment by pedrocasa** [comment]
Best way to solve it: don't let the user go to the upload page. If he tryes to upload an jpeg(ie) a notification should appear saying " invalid format" and he would stay on the landing page

**Comment by pedrocasa** [comment]
I totally agree with u
