### ISSUE TITLE
Define portal iPhone compatibility

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#455]
Simulators report the portal is broken on iphone. But other opinions show the opposite (maybe >7 it works).

![image](https://user-images.githubusercontent.com/1306173/38545854-536dfa72-3cab-11e8-886f-607d9ccf2b6d.png)

![image](https://user-images.githubusercontent.com/1306173/38545860-5926203e-3cab-11e8-8a79-1aab996d1b4c.png)

Then again, @eliawk  is reporting that on his iphone it is working

**Comment by felipegaucho** [comment]
@ya7ya also reportedly saw it working on an iPhone 7 Plus

**Comment by bent0b0x** [comment]
Works on my 7

**Comment by jellegerbrandy** [comment]
closing this then
