### ISSUE TITLE
Player on iPhone - just native controls

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#456]
On the iPhone the player controls are missing. There is just the play icon and when you click the video goes full screen and you can interact with it using the native controls 

![img_6bdeba258ed8-1](https://user-images.githubusercontent.com/362016/38546193-4bd58e78-3cac-11e8-9313-aa5310ed6323.jpeg)

![img_293549a89f2e-1](https://user-images.githubusercontent.com/362016/38546252-71db3e2e-3cac-11e8-9ea6-584d74faadf6.jpeg)

**Comment by bent0b0x** [comment]
I think this is expected. I don’t think it’s possible for us to display controls on mobile when the video is full screen.

**Comment by felipegaucho** [comment]
Expected behaviour, blame on Steve (Jobs)
