### ISSUE TITLE
UX specifications

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#46]
See here: [https://github.com/Paratii-Video/paratii-portal/wiki/Portal-Specifications](https://github.com/Paratii-Video/paratii-portal/wiki/Portal-Specifications)

**Comment by jellegerbrandy** [comment]
![img_20180113_110110878](https://user-images.githubusercontent.com/1306173/34905100-5be8d7c8-f852-11e7-9c96-d109aefd96a0.jpg)
![img_20180113_110136723](https://user-images.githubusercontent.com/1306173/34905101-6567c16a-f852-11e7-8727-654cdf149b19.jpg)
![img_20180113_110211811](https://user-images.githubusercontent.com/1306173/34905132-259d47fc-f853-11e7-8565-bd248eb3796d.jpg)
![img_20180113_110226691](https://user-images.githubusercontent.com/1306173/34905103-65b97f64-f852-11e7-8f13-d273296273c6.jpg)

**Comment by pedrocasa** [comment]
Just a question Jell. Does everyone can see how much I got on my wallet?
