### ISSUE TITLE
Password security discussion

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#477]
We have a potential security problem with our PIN. 

A PIN is a very weak type of password - if you have access to the thing-to-be-decrypted, you need only 10.000 tries to find decrypt the thing. 

The PIN serves two purposes:
- if someone has access to your device, she cannot just read your data/transfer your money. (typical scenario: yourfriend borrows your phone)
- if someone has access to your wallet info, he cannot just read yr data/transfer your money (typical scenario: someone steals your phone)

Our PIN is ok for the first scenario, but is pretty much useless in the second scenario (as it can be decrypted in 10K tries)

An extra bad thing about the PIN is that the user has no way of getting a better security: she cannot choose a strong password even if she wants to.

Possible next steps:
* Just accept this
* Forget about the pin, and just have the user choose a text password (>= 8 chars)

**Comment by jellegerbrandy** [comment]
(sorry for coming up with this only now. @eliawk , @pedrocasa , @felipegaucho , what do you think?)

**Comment by felipegaucho** [comment]
Have you checked https://beta.spankchain.com ?

Try the login/register flow.

Create password;
(confirm password)

THEN copy your words;
THEN paste them (spankchain just asks you to check you've copied)

THEN choose an username and email.
(and accept Terms & Conditions)

And Voilá.

What about doing the same rationale?

**Comment by jellegerbrandy** [comment]
yeah I checked, it's exactly what we are doing already!

(apart from the username/email at the end (which we have planned), and the card metaphor, which is unclear to me, and teh "terms and conditions", which is something we should DEFINITELY start talking about :-))

this issue is about what the password should look like, I know you guys like the pin very much because it was device-oriented, but  it is weak security, so I think we shoudl go back to a text password.

**Comment by pedrocasa** [comment]
"Create password;
(confirm password)

THEN copy your words;
THEN paste them (spankchain just asks you to check you've copied)

THEN choose an username and email.
(and accept Terms & Conditions)

And Voilá.

What about doing the same rationale?

"

There's a problem with the spankchain flow.

- At the beginning of the flow, they ask u for a password ( You have two options: continue/ Restore account)

- If you click on the restore button they will ask for the 12 words and them ask again for the password ( a modal just like the one that we saw at the beginning).


Maybe is better to show a modal before we ask for the password (as the gif below

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/30123644/39026599-58733dfe-4424-11e8-849a-f86b54cd8382.gif)
)

**Comment by eliawk** [comment]
@pedrocasa what happen if a user close the modal during the process, for example before entering username and email? are they blocking fields?

**Comment by pedrocasa** [comment]
I think the best option for this is: (is the same way that SpankChain works)

- the account only gonna be secure if the user clicks on the checkbox above the 12 words and them clicks on the continue button. //// If he doesn't click on the CONTINUE/CHECKBOX the account is not gonna be secure and he will need to do it again.

- the profile information doesn't have a close button (the user MUST inform the information before doing anything)
