### ISSUE TITLE
[secure account] Password strength

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#486]
At the moment there is no requirement on `password` **strength**. What are minimum requirements? 
@bent0b0x Do you know a good `npm` library to validate check the password strength?
@jellegerbrandy what do you think about it?

**Comment by bent0b0x** [comment]
I do not but I’d bet there are good options

**Comment by bent0b0x** [comment]
Also if we can define our requirements simply we can maybe get away with not using a library (in an attempt to pull in fewer things and keep bundle smaller)

**Comment by eliawk** [comment]
@bent0b0x for the smaller bundle we need to test this - https://github.com/Paratii-Video/paratii-portal/issues/484

but if we can avoid another library is better.

in case i was looking at these ones:
- https://www.npmjs.com/package/tai-password-strength
- https://www.npmjs.com/package/owasp-password-strength-test

**Comment by jellegerbrandy** [comment]
Let's just do a straightforward "at least 8 characters, at least 1 number"
