### ISSUE TITLE
[secure account] account migration could be long

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#487]
When you click on `Continue` in the modal when we show the Seed - you launch a migrateAccount() function that could be take a very long time.
@pedrocasa maybe we need to think about a feedback for the user? 
a loader? 
we display all the data we are transferring?

**Comment by jrgarou** [comment]
@eliawk a `disabled`  state on _continue button_ and _back button_ is already a good response for the user.

**Comment by jellegerbrandy** [comment]
Let's just do a straightforward "at least 8 characters, at least 1 number"

**Comment by jellegerbrandy** [comment]
The "migrateAccount" takes a long time because it needs to transfer all the videos. But this is a legacy case: normally, you will have no vids at all (and almost nothign to migrate)

**Comment by felipegaucho** [comment]
Agreed, people who undergo it will receive specific instructions and be aware of it.
