### ISSUE TITLE
[secure account] fix copy 

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#491]
- [ ] remove "mnemonic" on the "insert your 12 word phrase" page
- [x]  What does this mean?: "It will work for a password for fast transactions, but only if you are logged in". Just remove it
- [x] the password screen for "log in" says "new password" in the input field. Which is confusing, it should say "insert your password" 
- [x] "Key derivation failed - possibly wrong password" is too technical, should be "password is invalid"
- [x] "We found a private wallet on your localStorage, insert the password to decrypt it, and be able to use all the features of Paratii" -> "Please insert your password to use all the features of Paratii"
- [x] "Create a password for securing your account" -> "Choose a password"

**Comment by eliawk** [comment]
@jellegerbrandy i don't find the first one!
