### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#493]
We need them.

Example:

* https://spankchain.com/spank-wallet-agreement.pdf

**Comment by felipegaucho** [comment]
[Paratii Terms & conditions.pdf](https://github.com/Paratii-Video/paratii-portal/files/2045396/Paratii.Terms.conditions.pdf)

Would you give a look @jellegerbrandy ?
https://docs.google.com/document/d/1La29tLqN4Rr-Ak_pr1W4bl_4gI8siQn0JXeDEUAmgNM/edit?usp=sharing
@pedrocasa should we just have a no-interaction sentence, discreet and small, along the flow, indicating acceptance of it, with a link to the file?

**Comment by jellegerbrandy** [comment]
looks good to me!
