### ISSUE TITLE
[secure account] password messages

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#498]
We now have a terrible trial-and-error password handling which is hated all over the world :-)

- put a password "aaaa"
- "too short"!
- write "aaaaaaaa"
- "you must have a number"
- write"aaaaaaaa1"
- "you must a at least one upper case letter"
- curse, close the website, never return again

We need  one single message, written *before* enter the password, that states all conditions in one single phrase.

**Comment by eliawk** [comment]
@jellegerbrandy got it

**Comment by eliawk** [comment]
@jellegerbrandy @pedrocasa i will add a `forgot password` button in the ask password modal -> this button will ask the user the 12 words, and a new password
