### ISSUE TITLE
PLAYER - PARATII -- "play" icon and timeline bar

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#501]
Toddy tells us: https://github.com/Paratii-Video/paratii-js/issues/222

> hey guys, icon "play" just disappear sometimes in the beginning of timeline bar , we should decrease the size of timeline bar, may this issue will be fix.

**Comment by jellegerbrandy** [comment]
@jrgarou @bent0b0x @pedrocasa

**Comment by jrgarou** [comment]
This happens because of this buttons not use our `MainSVG`. 
It loads an SVG file with `mask-image`.
I think that all icons from interface should be a `<svg><use></svg>` [tag](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use).

(the notifications icons have the same issue)

**Comment by jrgarou** [comment]
@bent0b0x 
I'll update some SVG icons with [SVGIcon](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/foundations/Button.js#L84) and I make the same with those icons.

**Comment by felipegaucho** [comment]
Should we close this @jellegerbrandy @jrgarou ?
