### ISSUE TITLE
Password feedback is easy to miss and can be irritating 

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#515]
I saw someone else mention this, but although we tell the user upfront about the qualification for the password it is easy to miss and it would be better to get clear feedback on the user's password  before they try to submit it.

![passwordfail](https://user-images.githubusercontent.com/7697924/39387659-d3235a28-4a48-11e8-8899-1baee7c57cb6.gif)

**Comment by felipegaucho** [comment]
Closing it, tks @bent0b0x https://github.com/Paratii-Video/paratii-portal/pull/516
