### ISSUE TITLE
Discussion about the profile page

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#517]
To draw the profile page the first thing I did was to study other portals and see what functions existed within that page.

From these functions, I took the ones that made the most sense for Paratii and categorized them into 5different groups. (profile, my videos, finances, favorites, settings)

![web 1920 11](https://user-images.githubusercontent.com/30123644/39406651-4d88be8c-4b90-11e8-93ae-edb94068d76b.png)

(here are some layouts about how it's going to be like when can activate the settings/ finances etc
![web 1920 7](https://user-images.githubusercontent.com/30123644/39406659-87dd539a-4b90-11e8-9664-59f1672bbdec.png)

![web 1920 5](https://user-images.githubusercontent.com/30123644/39406652-4da971d6-4b90-11e8-8b61-5cef7a71adfd.png)

https://xd.adobe.com/view/cc9f3a9d-f9d0-458d-b64c-58c76d313ba9

there is still a lot to be done, and in the beginning, we will only have the page of my videos and the profile page (which would be a preview of how the profile is viewed by other people)

**Comment by felipegaucho** [comment]
Closing this, as the path to progress is outlined in https://github.com/Paratii-Video/paratii-portal/issues/528
And, the designs are recorded on https://github.com/Paratii-Video/paratii-portal/wiki/Design-Wiki#2-glimpse-of-a-further-iteration
