### ISSUE TITLE
Staking modal "continue" button must be disabled while the process of staking is ongoing

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#526]
At the moment, you click "continue" and you must wait quite a while, and you click again (and again and again). We should diable the continue button, just as we do with the save button on the form

**Comment by jrgarou** [comment]
I think we've have done this, @jellegerbrandy 
https://github.com/Paratii-Video/paratii-portal/pull/394

**Comment by jellegerbrandy** [comment]
:+1:
