### ISSUE TITLE
Make the "author" field for video uploads be filled automatically

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#530]
Make the "author" field for the video be filled automatically from the user nickname (attached to his address). Requires the signup+login flow fully functional.

**Comment by geckoslair** [comment]
actually user are write in the contract and CreateUser event is trigger from the portal? @jellegerbrandy

**Comment by eliawk** [comment]
https://github.com/Paratii-Video/paratii-portal/pull/579
