### ISSUE TITLE
scrollbars in search results :-(

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#534]
Probably not visible on safari:

![image](https://user-images.githubusercontent.com/1306173/39567911-c8a313b4-4ec0-11e8-9bf9-4a52c1830e5f.png)

**Comment by pedrocasa** [comment]
We need to hide part of the description. (Don't show more than two lines of it)

**Comment by bent0b0x** [comment]
Removed scrollbars and truncated video description to 2 lines
