### ISSUE TITLE
Enrichen video displays + correct colour in search

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#539]
- [x] Correct the background colour to match the design.

<img width="1247" alt="screen shot 2018-05-04 at 12 14 56 pm" src="https://user-images.githubusercontent.com/26517120/39635930-35fc27fa-4f95-11e8-965c-b52db9bfd07d.png">

VS: https://xd.adobe.com/spec/6e9bbad0-7d91-41e4-bc51-a1f31ff57882/#screen/81e820ab-bbb3-42d9-8b25-f4c30ccfa23f/search-future-needs1920

- [ ] Implement "author name" (check if https://github.com/Paratii-Video/paratii-portal/issues/530 is resolved)  and "published on", for each video.
- [x] Increase size of video duration box

**Comment by bent0b0x** [comment]
@felipegaucho I've fixed the background color and changed the duration font size (both on staging now or very soon). If you want either of them tweaked further just let me know!

**Comment by felipegaucho** [comment]
Very nice @bent0b0x, LGTM, only missing thing is the "author" (username).

Guess it depends on solving https://github.com/Paratii-Video/paratii-portal/issues/558 and pushing the whole profile to production, so feel free to break it down into a separate issue and close this one if you wish.

**Comment by bent0b0x** [comment]
Yup I don't think #558 is finished, I'll likely move that to a separate issue soon

**Comment by bent0b0x** [comment]
Closing in favor of #561
