### ISSUE TITLE
invalid RLP error

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#54]
This error was fixed in paratii-lib by applying a patch to web3.
However, it is not fixed ehre, because the patch does not arrive at the es6-compiled code - paratii-portal used the virgin web3js.

Since our PR in web3 is merged, we probably only need to wait until the next release to fix this error. If that takes too long, we can apply the same patch as in `paratii-lib`

**Comment by bent0b0x** [comment]
@jellegerbrandy I'm getting this locally whenever I run the chimp tests. Do you know of a workaround?
