### ISSUE TITLE
A better zero-state for search results

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#541]
Current one:

<img width="1268" alt="screen shot 2018-05-04 at 12 22 38 pm" src="https://user-images.githubusercontent.com/26517120/39636263-19235ce2-4f96-11e8-9044-7de5f701e30a.png">

@pedrocasa , when you have some spare time, let us know of ideas, and @bent0b0x can take care of it :) Don't be in a hurry!

**Comment by bent0b0x** [comment]
What is wrong with my beautiful zero state design? 😜 

Just kidding, happy to implement a much better design when we have it.

**Comment by bent0b0x** [comment]
Hey @pedrocasa, just wondering if you have any thoughts as to what the zero state should be?

**Comment by jellegerbrandy** [comment]
For me it looks fine, if there are no objections from @pcasa I just as well
close it.
