### ISSUE TITLE
Implement 2nd simple profile page

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#542]
## 2. Superbasic profile + options
Put the superbasic profile card in the top left corner, add the options on the menu below (still all locked). We can put the videos of the account on the empty right side, still in the ugliest/simplest form possible.

### 3. Differentiate between liquid PTI / staked PTI

Transform the "balance", under the username, into the divided liquid / staked balance viewer that @pedrocasa has designed.
Will become separate issue. 

### 4. Put videos of the guy [m/f] on the right

As Pedro designed, but can be unprecise about details & polished UI as for now.

### Next steps

Informed by what we learned in the previous steps, will include:

* Statistics about video (when uploaded, popularity, stuff like that)
* TCR challenge information about your videos (which of my vids is cahllenged? Which are fine?)
* TCR active particpation (i.e. discovery, challenging, voting)
* Transaction history
* Playlists (?)

**Comment by pedrocasa** [comment]
@jrgarou 

This is the specs link (Felipe is referring to the 2nd page)
 https://xd.adobe.com/spec/38f08784-7e68-47d4-960e-bbf6ba77f6f7

This is the prototype link (Felipe is referring to the 2nd page)
 https://xd.adobe.com/view/cc9f3a9d-f9d0-458d-b64c-58c76d313ba9

My XD file has been corrupted but I will redesign it as soon as I can

**Comment by jrgarou** [comment]
@pedrocasa There's no "Curantion + subnav" anymore?

![image](https://user-images.githubusercontent.com/320157/40329672-a9d3ff5c-5d20-11e8-95d1-d3554a96d5b7.png)

**Comment by pedrocasa** [comment]
still have, I just did not update this file because the file was corrupted

**Comment by geckoslair** [comment]
@pedrocasa maybe the add placeholder on "My Videos" can be on the top of the grid, not at the end.

**Comment by felipegaucho** [comment]
@jrgarou this is the issue we spoke of, today, in the call, which would be awesome if you could lead, supported by Pedro, this week. Would be amazing to have that sidebar menu + wallet (even if not working with all the right data yet) by the end of the week (steps 2 and 3) :)
