### ISSUE TITLE
Autoplay in portal not always working

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#544]
- visit https://staging.paratii.video/play/TXWzBRXgWytP
- the video does not play w/o user interaction (maybe it will sometimes, there could be a race-case)

**Comment by bent0b0x** [comment]
This is almost surely due to new restrictions in chrome when it comes to autoplay (https://developers.google.com/web/updates/2017/09/autoplay-policy-changes).

Safari has also implemented similar restrictions, in that by default (I believe) autoplay is disabled on all pages.

We need to detect if autoplay fails and then show the start screen if so. So far the clappr event system doesn't seem to help with this, but that is what our solution should be (most likely).

**Comment by bent0b0x** [comment]
Currently, the issue is that when we try to play the video w/ clappr and chrome and/or safari blocks it, I'm not sure if we get notified by an event that the player has stopped. Thus, we can't respond and show the start screen.

One quick patch is to just not autplay videos ever for now

**Comment by bent0b0x** [comment]
This seems broken again

**Comment by jellegerbrandy** [comment]
sems a browser issue
