### ISSUE TITLE
SVG continuously requested as video plays

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#547]
When a video plays, the browser requests `card-bg.svg` multiple times a second. This cannot be good for performance.

We should handle his SVG as we do other SVGs so this no longer happens. It should only be loaded 1x.

**Demo**

![svgfail](https://user-images.githubusercontent.com/7697924/39674401-6516013e-5119-11e8-9b59-8fdf81952db8.gif)

cc @jrgarou

**Comment by jrgarou** [comment]
I agree. But why these requests are happening, @bent0b0x?

**Comment by jrgarou** [comment]
Anyway, this `Card` should have the `nobackground` prop

**Comment by bent0b0x** [comment]
Yeah, I'm not really sure why were were making all of these requests but for now the attached PR is a quick fix
