### ISSUE TITLE
Systems Architecture (discussion)

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#55]
# System Architecture

We have two consumer-facing apps:
 - portal 
 - player
 
This may in the future be extended with other things, like a mobile application.

Both make use fo paratii-mediaplayer (for playing files from ipfs) and paratii-lib (does the heavy lifting)

We have a number of requirements for the system setup:
 - The setup should avoid duplication of code as much as possible. 
  - Portal and player will share a certain amount of logic (how to save wallet info in the browser, how to create an account)
  - Portal and player share graphical design
 - We'd like both apps to share the same architecture stack (easier for developers and devops)
 - Both apps need a server side process to set the correct headers for our pages (it will also help with optimizing)
 - Incidentally, both apps will be deployed to the same domain and on the same machine something like `paratii.video/play/1` for the portal and `paratii.video/embed/play/1' for the embeddde version - so it makes sense to have them even share the same server-side process.

Proposal:

  -react/redux app
  - Add an express layer to add server-side rendering (using this  type of pattern https://css-tricks.com/server-side-react-rendering/ ) - i.e. adding express as an extra "indepdendent" laye ron top of the react app)

Open question: 
  - To me it seems logical to develop the two apps in the same repo, but @bent0b0X does not seem to agree... will it be easer to develop the two apps in two different repo's, or in a single one?  I cannot seem to find a good example of building different apps from a single code base.

**Comment by bent0b0x** [comment]
After further consideration, I agree with your proposal to add this server layer in the same repo

**Comment by bent0b0x** [comment]
FYI, I am working on this now and should have a PR up for review tonight (tomorrow morning for you guys ;P)

**Comment by jellegerbrandy** [comment]
With regard to the PR, here's what I had in mind: 

 * With regard to "system architecture", there is really no distinction between "embeddable player" and "portal". There is a single codebase that creates components that can be embedded, and creates pages for the portal. 
 * The system needs a server-side process that sets the correct headers on the pages (and serves the right content at the appropriate URLs). This can be a relative simple express-layer on top of the react app.
 * For optimizazation purposes (i.e. this is more a devops question), it makes ssense to have different webpack builds for different parts of the app: in particular, the pages that are to be embedded should be as light-weight as possible.

**Comment by bent0b0x** [comment]
I think the PR is good on points 1 and 3 (but feel free to refute that :) ). On the second point, yes right now the server process is only for serving up the embed html views. I can rework the server to encompass the entire app

**Comment by jellegerbrandy** [comment]
Agree
