### ISSUE TITLE
Username and email not being correctly displayed after registration

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#558]
Even though I just registered them with a new account, @jrgarou @eliawk.

<img width="840" alt="screen shot 2018-05-07 at 4 56 46 pm" src="https://user-images.githubusercontent.com/26517120/39722016-b3c2e12c-5217-11e8-9809-14833d831f07.png">

**Comment by jrgarou** [comment]
@felipegaucho @eliawk Looks like the input information on the `ModalProfile`(👇) isn't being saved.


![image](https://user-images.githubusercontent.com/320157/39724888-6aed0488-5220-11e8-9e9c-31325273aa67.png)

**Comment by jellegerbrandy** [comment]
I checked the whole "pipeline", and the save works and db indexes it, i.e. the following works as expected:

    paratii.users.update(myAddress, {email: 'somemail', name: 'somenmae'})
   paratii.users.get(myAddress) // returns the saved info

So I suspect something goes wrong in the frontend. This is a bug in production, guys, it needs some attention: @eliawk , can you look at this?

**Comment by eliawk** [comment]
@jellegerbrandy i'll check

**Comment by eliawk** [comment]
@jrgarou the data are correctly saved

**Comment by eliawk** [comment]
@felipegaucho @jrgarou @jellegerbrandy now is fixed here https://github.com/Paratii-Video/paratii-portal/pull/563
