### ISSUE TITLE
Search with 0 seconds

### ISSUE THREAD

**Issue by lupape** [Paratii-Video/paratii-portal#559]
Search videos with 0 seconds should be excluded because it is taking the user to nowhere.
<img width="1053" alt="0seconds" src="https://user-images.githubusercontent.com/5768296/39723800-4d2092e2-521d-11e8-97b3-e0109ce51709.png">

**Comment by felipegaucho** [comment]
Can we just do a cleanup on all vids <00:01?

**Comment by bent0b0x** [comment]
Yes, these are probably videos that were uploaded in a bad state for whatever reason. I think as @felipegaucho suggested we should just delete these. Thoughts @jellegerbrandy ?

**Comment by jellegerbrandy** [comment]
+1

we have no "deletion" but perhaps @geckoslair can filter the results?

**Comment by geckoslair** [comment]
There are two types of activities:
- cleanup wrong loaded video ( i'll cleanup from the db )
- set staked=true in the request @bent0b0x ( can you manage this )

**Comment by bent0b0x** [comment]
Done via https://github.com/Paratii-Video/paratii-portal/pull/575
