### ISSUE TITLE
Add author name to search results

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#561]
When #530 is resolved, we should display the author name for videos in the search results:

![image](https://user-images.githubusercontent.com/7697924/39735765-0a620322-524b-11e8-897e-8031c06227f3.png)

[Link to design](https://xd.adobe.com/spec/6e9bbad0-7d91-41e4-bc51-a1f31ff57882/#screen/81e820ab-bbb3-42d9-8b25-f4c30ccfa23f/search-future-needs1920)

This is replacing #539

**Comment by bent0b0x** [comment]
I think we've been thinking about the video authorname incorrectly actually. We should not attach an explicit `author` field to the videos at upload or publish time, because I'm sure we will enable people to change their usernames and then we'd have stale `author` fields.

@geckoslair, can we make it so that the db will not only include `owner` address in video query results, but also the db will fetch and attach `ownerUsername` (or `author`) to resulting JSON as well? I think we should do this on all calls to `/videos`, whether it is for search or just fetching one video.

Let me know your thoughts!

**Comment by jellegerbrandy** [comment]
We'd already decided to remove the author field from all the forms, and I think we've done that (looking at staging). 

This basically means that new videos will not get a separate "author" field (they'll just get the name fo the uploader - note that this is not perfect either and we may want to change that again in the future)

I'm not sure what to do with the "old" author names in the existing videos. One of 3 options:

1) keep the legacy, and use a scheme such as ben proposes above
2) remove the authro field from everything, and just loose the existing author names
3) remove the author field from everything, but create some user accounts in which we copy the author field (if we have collisions, we will just choose one).

**Comment by jellegerbrandy** [comment]
personally, I'd be for 2, at most 3.

**Comment by jellegerbrandy** [comment]
wait, I see this is already discussed in https://github.com/Paratii-Video/paratii-db/issues/134, so we continue it there..

**Comment by geckoslair** [comment]
closed at paratii-db side

**Comment by bent0b0x** [comment]
Working on this 👍
