### ISSUE TITLE
Do not show video start button until clappr player has loaded

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#562]
Right now, we show this button 👇 even before the clappr player has loaded. This means that a user, especially on a slow connection, could click the play button and have it do nothing at all.

![image](https://user-images.githubusercontent.com/7697924/39736009-37bf0404-524c-11e8-9747-8844a577d286.png)

We should hide the start button (and the controls bar) until the clappr player has been instantiated. Right now when we hide the start screen we see the controls (assuming the video overlay is visible), so this will require a change to that logical coupling as in this case we want to hide _both_ the start button and the controls bar.

This issue was spawned by a discussion in #549.

cc @jrgarou

**Comment by felipegaucho** [comment]
Didn't notice in production @bent0b0x , should this be closed or is it still there?

**Comment by bent0b0x** [comment]
This is kind of a UX edge-case, and on slow connections _could_ be annoying or confusing. I think it still persists on production so I would leave it open.

That said I don't think we need to consider this a high priority

**Comment by bent0b0x** [comment]
Actually, I think you're right and this is resolved. Closing :)
