### ISSUE TITLE
[edit profile] no underline if it is not an input box

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#570]
this seems editable, but it is not:

![image](https://user-images.githubusercontent.com/1306173/39927996-5eb4c806-5534-11e8-994f-3cf981aefdc2.png)

**Comment by jrgarou** [comment]
I agree, @jellegerbrandy. There's no reason to be an input - even with a `readonly` property.

@pedrocasa, what you think about to change for something like this:

![image](https://user-images.githubusercontent.com/320157/39931879-0fb6cb1a-5515-11e8-8584-b7754308681d.png)

**Comment by pedrocasa** [comment]
I think it's better than the current one.

Nice work
