### ISSUE TITLE
Make username required in account secure flow

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#571]
Right now, you can dismiss this modal (by clicking X or by clicking outside of the modal)

![image](https://user-images.githubusercontent.com/7697924/39934322-720ecb66-5513-11e8-93b7-bd3713ec2564.png)

Let's not make this optional, because we want reasonable usernames for video authors/creators throughout the system.

**Comment by pedrocasa** [comment]
On my first designs, it wasn't optional.
If someone could fix it would be nice

**Comment by felipegaucho** [comment]
Tks @bent0b0x 👊
