### ISSUE TITLE
Filter search results by staked parameter

### ISSUE THREAD

**Issue by geckoslair** [Paratii-Video/paratii-portal#572]
Please add staked=true as extra parameter in the search query:

- **from:** https://db.paratii.video/api/v1/videos/?keyword=video&limit=12&offset=0
- **to:** https://db.paratii.video/api/v1/videos/?keyword=video&limit=12&offset=0&staked=true

**Comment by bent0b0x** [comment]
I'll put up a PR but won't merge until the issue mentioned above is resolved 👍

**Comment by bent0b0x** [comment]
@geckoslair is this still not working? Filtering on the FE seemed to be fine but let me know if not!

**Comment by geckoslair** [comment]
sorry guys i've missed the task, please open paratii-db related issue on paratii-db repo next time, that would help me =). I've deployed on staging the fix.
