### ISSUE TITLE
Move mock-server to its own module

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#578]
The [mock-server](https://github.com/Paratii-Video/paratii-portal/tree/dev/mock-server) is now used for mocking endpoints in some functional tests. This module should/could be moved outside of `paratii-portal` into a standalone module.

**Comment by jellegerbrandy** [comment]
I don't understand why. What do we gain by doing this?

**Comment by bent0b0x** [comment]
This is not a priority, but this module is useful outside of the context of the portal. I built it in the portal for speed/convenience

**Comment by jellegerbrandy** [comment]
ok, I get it :+1:
