### ISSUE TITLE
Delay in securing wallet is bad UX

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#580]
**Problem**
When the user secures their wallet, there is a several second delay before the securing is complete. During this time, there is no loading spinner/indication that anything is happening.

**Demo**

![securefail](https://user-images.githubusercontent.com/7697924/40089577-61102ae8-587a-11e8-9b5f-15031f7223fe.gif)

@pedrocasa thoughts on what we could do here to mitigate? I think the `'Securing your wallet'` notification is supposed to show up immediately, but it is not. Perhaps it is as simple as fixing that.

**Comment by felipegaucho** [comment]
Let's just use the notification (at the right time) @bent0b0x ?
Then, on next week, one of the stuff @pedrocasa can dedicate himself to is reviewing all our delay handling on UX - if we should reuse the generic spinner used on the portal's main initial loading, or have a specific component...

**Comment by jellegerbrandy** [comment]
Note that this is not optimizable (afaik): the security of the private key
is directly proportional to the amount of computing it takes to generate it.
