### ISSUE TITLE
Video Time passes the total duration of the video 0.o

### ISSUE THREAD

**Issue by lupape** [Paratii-Video/paratii-portal#589]
The size flagged in the video is 0:44 and the video goes to 0:45.
<img width="827" alt="screen shot 2018-05-21 at 12 23 23 pm" src="https://user-images.githubusercontent.com/5768296/40315499-ef1c2d8e-5cf1-11e8-9585-a985fb29e1e2.png">

**Comment by bent0b0x** [comment]
A fix is in progress via #626

**Comment by felipegaucho** [comment]
Fixed already.
