### ISSUE TITLE
Email Confirmation UX

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#590]
In order to clarify how the email flow is gonna be I create this diagram (XDLINK_

https://xd.adobe.com/view/c654a541-723e-4329-b0df-89a370466cc1

- The user submits his email on the login process 
- The user ends the registrations process
- The user goes to his email and confirms his account by clicking on a button/link (the PTI is only available if he clicks on it)
- The link is going to take the user to the profile page. A notification box is going to appear "Email confirmed! Congratulations, you have earned XX PTI. (This notification will only appear on this link)

**Comment by jellegerbrandy** [comment]
looks perfect to me

**Comment by jellegerbrandy** [comment]
unfortunately, at the moment we cannot do the last step that you indicated, because we do not have (yet) "automatic login". i.e. ifyou click on the link, you are not logged in. We are now implementing just a simple landing page in #594

**Comment by pedrocasa** [comment]
Here's the design of future version of the email 

![email](https://user-images.githubusercontent.com/30123644/40441670-0f6c5b3e-5e98-11e8-89b9-ae51bba89694.png)

specs
https://xd.adobe.com/spec/3857096d-f761-4226-b496-7b54a91e7af9

(I've already updated the email flow link as well)

**Comment by geckoslair** [comment]
Nice! @bent0b0x @jrgarou what you think about it?

**Comment by jrgarou** [comment]
looks fine, @geckoslair 
We probably should use images only.

**Comment by pedrocasa** [comment]
Even for mobile?

**Comment by jrgarou** [comment]
@pedrocasa how it'll look like at mobile?

**Comment by jrgarou** [comment]
@pedrocasa will be great if we could be more "vertical" or less "wide"

**Comment by jellegerbrandy** [comment]
guys, just a headsup so you know what you are getting into: there are 100s
of email clients out there, there is no guarantee how the mail will be
rendered. Just saying: keep it simple.

**Comment by jrgarou** [comment]
>guys, just a headsup so you know what you are getting into: there are 100s
of email clients out there, there is no guarantee how the mail will be
rendered. Just saying: keep it simple.


I don't get it, @jellegerbrandy. What do you mean about _"keep it simple"_?
Besides the wide format, the @pedrocasa design is pretty simple.

**Comment by jellegerbrandy** [comment]
Well then, keep it that way :-)

(It seems to have a background image, though, which is pretty impossible to
get right. Try it out :-))

**Comment by jellegerbrandy** [comment]
closing this generic issue, creating a new one just for implementing the email design
