### ISSUE TITLE
E-mail confirmation text

### ISSUE THREAD

**Issue by dtquandt** [Paratii-Video/paratii-portal#596]
Ideally, eventually the e-mail will be in the user's language and nicely formatted. For now, this should suffice:

"Thank you for registering at Paratii! Click the link below to confirm your e-mail and earn 25 PTI, enough to upload 5 videos.

%URL%"

The line break between the text and the URL would be nice to have, compared to the run-on we have right now.

**Comment by jellegerbrandy** [comment]
we also need a "from" address. Shall we put "we@paratii.video"?

**Comment by dtquandt** [comment]
That seems fine for now but I imagine it would be prudent to have a noreply@paratii.video or useraccounts@paratii.video or something like that eventually.

**Comment by jellegerbrandy** [comment]
closing this in favor of #605
