### ISSUE TITLE
webpack error: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#597]
```
WARNING in ./node_modules/paratii-js/src/paratii.eth.js
506:20-58 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/paratii-js/src/paratii.eth.js
 @ ./node_modules/paratii-js/src/paratii.js
 @ ./src/scripts/utils/ParatiiLib.js
 @ ./src/scripts/actions/VideoActions.js
 @ ./src/scripts/containers/PlayContainer.js
 @ ./src/scripts/embed/index.js
```

**Comment by bent0b0x** [comment]
Looking at this now

**Comment by bent0b0x** [comment]
This is a `paratii-js` issue.

Look at [this require](https://github.com/Paratii-Video/paratii-js/blob/b59c766ab3cfc43906fd2cf2f13c34c0d350a4aa/src/paratii.eth.js#L172) and [this one](https://github.com/Paratii-Video/paratii-js/blob/b59c766ab3cfc43906fd2cf2f13c34c0d350a4aa/src/paratii.eth.js#L180). They are expressions.

How many contract names are there and how dynamic are they? I recommend hard-coding them, similar to how is done [in the portal here](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/utils/AppUtils.js#L63-L87).

**Comment by jellegerbrandy** [comment]
Yes, I just wrote those portal lines yesterday :-)
There are about 10 contract names, but will become more, and it is much
cleaner to use an expression.
Perhaps we could not "require" those files, perhaps, but just fs.read them
- they are just data, after all, not real code to be parsed and minified.
Let's wait for the PR of lorenzo, who is reconstructing these json files,
and then fix it.

**Comment by jellegerbrandy** [comment]
this is being worked upon in the  fix/dependency_is_expression branch in paratii-js

**Comment by jellegerbrandy** [comment]
the issue is actually from both portal and paratii-js

this is the parati-js issue: https://github.com/Paratii-Video/paratii-js/issues/273
