### ISSUE TITLE
Design.Portal Upload and Manage videos

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#60]
Upload Tool (and also a way to manage the videos that already have been uploaded)

Yesterday I tried to create a UX upload page for the portal that could join the function of uplodar a video with the managing of the videos that have already been uploaded in the past (like a page my videos).

The idea would be to keep on the same list the videos that are uploading and those that have already been uploaded. The user will edit them according to their needs.
I do not know how this idea can become confusing for the user so I ask everyone's help to analyse if it's possible

There's still a lot of work to do with this pages, but I think it would be nice if everyone can see the process stage

[upload_flow.pdf](https://github.com/Paratii-Video/paratii-portal/files/1645322/upload_flow.pdf)

**Comment by jellegerbrandy** [comment]
I think it looks very nice :-)

- I thnk you upload a low-res version of the images - the texts are hard to read
- I do like the soltuion of having the "files being uploaded"  on the left in the edit screen
- in a first iteration we  just do the flow for a single video, and so we will not implement the left thing yet, though
- to understand your intentions: assume that the UP_03 screen will not be very different (or even exactly the same) as the generic "edit your video info" screen. (I mean, you can also edit videos that are already uploaded, and it would have the same UX, I think). Agree? 
- w.r.t. the "tags" screen. We will (in the future!) also want to add some more organizing of videos (in playlists, etc)
- one thing that is probably important (and needs to be explained) is the "status" of the video. Roughtly, we go through the following stages (which ahppen **while** you are editing the video info): 
   - upload to local ipfs node (= pretty fast)
   - uploading to ipfs network (in particular, upload to the transcoder) [_now your video is saved and you can turn off your computer without problems_]
  - upload done
  - start transcoding
   - transcode the video (= pretty long)
  -  transcoding done: video is ready for viewing and sharing

**Comment by jellegerbrandy** [comment]
Thinking about it, actually the "please don't leave" situation is pretty much standard UX and most people are used to it: if you uplaod a file, you see  aprogress bar, and if you close the browser before that progress bar has finished, your file will not have been uploaded. Our case is exactly like that...

**Comment by jrgarou** [comment]
Hey @pedrocasa what beautiful uploader, man. Awesome

I think the flow could be more simple.
What you guys think about this approach(I destroyed Pedro's design):

- The start point. Here he decide where to go. It's important highlight the "drag & drop" area. 
![00uploader-0](https://user-images.githubusercontent.com/320157/35153275-ff105cc8-fd0c-11e7-8d3e-8e18a955cbab.png)
- Whatever user decide, it comes to this screen.
(@jellegerbrandy @ya7ya There's something in youtube/vimeo uploader that could be different here?)
So we create one single component and use it in the uploader and edit video pages. 
No pagination. No videos navigation(a vertical list). 
The `/uploader` "component" and `/edit-video` "component" are very similar, besides its needs(we could implement by a parameter or something like that, or extends another component).

![00uploader-1](https://user-images.githubusercontent.com/320157/35153591-468607c8-fd0e-11e7-9fe7-6ac6be9d2710.png)

![00uploader-2](https://user-images.githubusercontent.com/320157/35154906-24235ba4-fd13-11e7-84ce-03b129406554.png)


Makes sense? What you think, guys?

**Comment by pedrocasa** [comment]
Some changes that I've made focusing on our current needs 
![upload_flow](https://user-images.githubusercontent.com/30123644/35294737-747c7dd0-005e-11e8-96b8-f9a6ad74762b.png)

**Comment by pedrocasa** [comment]
Some changes that I've made focusing on our current needs

![upload_flow](https://user-images.githubusercontent.com/30123644/35295069-4fafcea2-005f-11e8-8606-018d4ff3326f.png)

**Comment by bent0b0x** [comment]
One question I do have, re our message "Upload to local IPFS node".

To the more savvy user, this probably makes sense. But to the average user, I would think this verbiage could be confusing and possibly scare them away. What are we actually trying to convey to them here? Are we trying to indicate that they cannot close their browser during this process? If so, what if we make _that_ the focus of the message and possibly show details (e.g. IPFS info) on a tooltip?

**Comment by jellegerbrandy** [comment]
I think it is best to think of it it as a two-stage process:

- upload the file [user must wait until this finished]
- transcode it [happing outside of users control - can take a really long time]

Wrt the uploading:
- It is not "uploading to local ipfs node" - that is very quick and not so interesting. It is upoading "to the cloud" that we are interested in here.
- In terms of UX, I think this screen si fine (excpt for the text, which could become "Uploading your file"

Wrt transcoding:
- this is happening far awy and is not under the uuser's control. It can even happen hours later (if the transcoder is busy). So here, a progress bar is less useful. We can just say "your file we be transcoded, please check later". 
- (We will also send them an email if we are finished (ina later iteration), so this could be a point where we ask theuser to provide that email)

**Comment by mrocha94** [comment]
I think we don't need the UP_01 and UP_02, on UP_03 should has a area to upload videos and for youtube, a "toggle button" that hides the dropzone and show a text box to paste the link. I don't know if the "video manager" screen look too messy.

**Comment by jrgarou** [comment]
@bent0b0x @jellegerbrandy forget about the text. It's generic. Everything is just a _mockup_.
This area is to inform the user about anything we want. In case, infos about **uploading**.

> Wrt transcoding:
this is happening far awy and is not under the uuser's control. It can even happen hours later (if the transcoder is busy). So here, a progress bar is less useful. We can just say "your file we be transcoded, please check later".
(We will also send them an email if we are finished (ina later iteration), so this could be a point where we ask theuser to provide that email)

@pedrocasa about the **transcoding** state we can use our component side space(uploader/embed area) to show this information - just like @jellegerbrandy suggested(_"your file we be transcoded, please check later"_).

![image](https://user-images.githubusercontent.com/320157/35625719-7b62ad6e-067a-11e8-84e8-f98833677f01.png)

**Comment by pedrocasa** [comment]
New ux according to monday call

![flow](https://user-images.githubusercontent.com/30123644/35864209-3f9bc7a8-0b38-11e8-869e-32d36fa7a6cc.png)

**Comment by pedrocasa** [comment]
New corrections 

![flow_02](https://user-images.githubusercontent.com/30123644/35881615-88a0d29c-0b68-11e8-9238-a16e80380104.png)
