### ISSUE TITLE
show notification when sending mail

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#603]

**Comment by eliawk** [comment]
https://github.com/Paratii-Video/paratii-portal/pull/621

**Comment by eliawk** [comment]
https://github.com/Paratii-Video/paratii-portal/blob/7cb9e6b8b614e1b4521c4fcd70c5380499ded925/src/scripts/components/widgets/modals/ModalProfile.js#L88
