### ISSUE TITLE
portal does not show balance!

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#604]
The balance in the top-right corner is always 0

**Comment by eliawk** [comment]
@jellegerbrandy this seems a problem related to the transaction itself, not just a portal issue

**Comment by jellegerbrandy** [comment]
why do you think that?

**Comment by eliawk** [comment]
because the Reducer already use Bignumbers - and anyway i can't made a correct transaction on verify mail. I've always get errors

**Comment by jellegerbrandy** [comment]
This was a misunderstanding (confused wei with pti) with a bug in the pti distribution thing
