### ISSUE TITLE
Design homepage of portal

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#611]
@pedrocasa is designing it, to be simple, focusing on one thing or two at most. Like Vimeo's search page: <img width="1259" alt="screen shot 2018-05-23 at 11 59 45 am" src="https://user-images.githubusercontent.com/26517120/40432783-dcb7230c-5e80-11e8-974e-25611f79913d.png">
Or wetransfer's landing page:
<img width="1276" alt="screen shot 2018-05-23 at 11 53 59 am" src="https://user-images.githubusercontent.com/26517120/40432789-de20453e-5e80-11e8-8a54-09cff16c40e3.png">
Or a simple grid design.

**Comment by pedrocasa** [comment]
this could definitely save us from making a landing page where we need to have lots of content or curation of what videos would be on that page (👍👍👍)

**Comment by jellegerbrandy** [comment]
@pedrocasa , what is the status of this?

**Comment by pedrocasa** [comment]
Here are the designs of the landing page:

![logged](https://user-images.githubusercontent.com/30123644/40630011-5ea76df4-62a5-11e8-8a25-cf7375633df1.png)


https://xd.adobe.com/view/4a374bcf-fd6a-4bee-a436-49ece2060631

**Comment by jrgarou** [comment]
@pedrocasa the _blur effect_ is just possible on Safari

**Comment by pedrocasa** [comment]
No problem, let's play safe (links updated)

![non-logged](https://user-images.githubusercontent.com/30123644/40668660-7d1ba26e-633b-11e8-9893-e30b4270a95d.png)
