### ISSUE TITLE
New upload video, FE improvements

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#616]
@jrgarou on the BR `feat/upload-video` there a few FE things to improve - the upload button at the end of the list and the staked button 

<img width="1125" alt="schermata 2018-05-25 alle 11 33 18" src="https://user-images.githubusercontent.com/362016/40537617-a471e762-600f-11e8-8fde-a81e35f9a697.png">
<img width="1131" alt="schermata 2018-05-25 alle 11 34 01" src="https://user-images.githubusercontent.com/362016/40537618-a490ac7e-600f-11e8-82a1-110c1e37221c.png">

**Comment by jrgarou** [comment]
@pedrocasa @eliawk  Today we have 3 uploaders:

- ![image](https://user-images.githubusercontent.com/320157/40560349-1606ba4a-6030-11e8-8f69-1d436c843b6b.png)
- ![image](https://user-images.githubusercontent.com/320157/40560515-a6f3a482-6030-11e8-9477-2d0f7d39dac8.png)
- ![image](https://user-images.githubusercontent.com/320157/40560550-bcea034e-6030-11e8-8148-d39f24cc8d29.png)


What you think about to create one uploader all cases?
With a 100% width and:
- put it at top of **/upload** page
- put it at bottom of **/upload** page with loaded videos
- put it at bottom of **/profile/my-videos**

**Comment by felipegaucho** [comment]
@pedrocasa what's your opinion?

**Comment by pedrocasa** [comment]
We should definitely use a single upload button. I prefer the one that only has the + and the sentence (it's easy to use and easy to design in different places).
The only thing that I disagree with jr it to put it on the bottom of the my video page. I think it's easier to our users find it with it is side by side with the videos (as the picture that jr sent)

**Comment by jrgarou** [comment]
> The only thing that I disagree with @jrgarou it to put it on the bottom of my video page. I think it's easier to our users find it with it is side by side with the videos (as the picture that jr sent)

@pedrocasa  @felipegaucho 
In `/my-videos` the list is most import thing. The uploader is secondary. 
When the row is full the uploader goes to the bottom anyway - and at some responsive point too.
And I don't think the uploader going to be hidden or hard to see because of that.

**Comment by pedrocasa** [comment]
![frame io 1](https://user-images.githubusercontent.com/30123644/41307908-d9461874-6e50-11e8-8f08-8fb8218af19a.jpg)

this action works perfectly in the  https://frame.io/

It's exactly just like our my videos page
