### ISSUE TITLE
"you have recevied..." is show in wei (not pti)

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#620]
![image](https://user-images.githubusercontent.com/1306173/40552415-de3207b8-603f-11e8-96bc-7fb6820e0911.png)

**Comment by eliawk** [comment]
@jellegerbrandy it has been fixed here
https://github.com/Paratii-Video/paratii-portal/blob/08bf260b9e76cec98a691c2958db412fdd5ba6a8/src/scripts/components/pages/MailVerify.js#L42

don't know why is not in production

**Comment by eliawk** [comment]
rebuilding circle everything ok
