### ISSUE TITLE
Add a login to the player

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#630]
Since we have no login flow on the embedded player, and leave no cookies for "automatic login", in practice, all the views in the embedded player aer "anonymous". 

possible actions:

* keep wallet open in de session (i.e. less secure0
* add explicit login in embedded player and insist user logs in

**Comment by felipegaucho** [comment]
I'd say: keep it all anonymous, user is not prompted to log in. 

In-player, we'll have one simple input form for login or password (other cases, e.g. tipping). If user finds its way till it (clicks on profile icon, prompt login options), he can login and take control of acc. After it, we can keep / maintain it during tab-switching, session ends = logs out.

We can "lose" funds from the old account for now. Let's worry about transferring them from old anonymous acc. to the newly secured one when the case is more concrete.

**Comment by jellegerbrandy** [comment]
Just to be clear: it is not only about the money. It is also about:

1) reading personalized data (i..e get stuff that _you_ like we need to identify you, and we do that with the address)
2) writing data (or offering on the market): such as: which videos you saw, if you liked them
3) payments etc.

so while, for now, with the functionality we implemented, remaining anon is fine. But in the medium term, we need to find a way to handle this.

We have I think to ways to go:

* keep the user "logged in" with a session cookie. This is what users are used to. But in our case, this means keeping the wallet unencrypted in the browser, which is a security concession we may or may notwant to make
* have different accounts/address that are somehow connected in paratii. I.e.one "low value" transactions, which can be a bit more risked, and one "high value" that we  keep superprotected

(or a combination of the two)

**Comment by felipegaucho** [comment]
Closing this since we're not exactly implementing it. Ideal option here would be something along the lines of the latter!
