### ISSUE TITLE
SES verification failed for paratii.video

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#637]
so all our mails will go to smap :-/

**Comment by jellegerbrandy** [comment]
https://us-west-2.console.aws.amazon.com/ses/home?region=us-west-2#verified-senders-domain:

**Comment by jellegerbrandy** [comment]
we are settiing the from temporarily to player.paratii.video, until the domain is verified ("up to 72 hours')

**Comment by felipegaucho** [comment]
damn. Hopefully solved by today :)

**Comment by jellegerbrandy** [comment]
managed to do it using iwantmyname anyway
