### ISSUE TITLE
transfer the PTI from the previous ptidistributor back to owner

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#640]
We found a PTIDistributor contract on 0xC81eeF444B7c3Bf2f5B97Cf056B5Dc04EcdF5F55
The PTI balance of the PTIDistributor is: 101000000000000000000000 (101000 PTI)
The owner of the PTIDistributor is: 0x7e7e5Db705113F3693F030BB8f1fB029E59549eF
The registry of the PTIDistributor is: 0x0d03db78f5D0a85B1aBB3eAcF77CECe27e6F623F

**Comment by felipegaucho** [comment]
@jellegerbrandy I'm closing this, let me know if you deem important to keep an eye on it 👀
