### ISSUE TITLE
Move edit profile operations into redux

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#642]
We should not do complex data operations within our components. Our codebase may get out of hand if we have a mix of business logic in components and in redux actions. [This instance method](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/ProfileEdit.js#L136-L182) is a prime candidate to be moved into a redux thunk, and we should do so. 

Our components should be mostly presentational and not worry about data operations.

**Comment by eliawk** [comment]
@bent0b0x what do you mean?
in that component the redux part is related to the notification, but the logic part is just related to **paratii.js** `paratii.users.upsert`.
how can we move all this to redux?

**Comment by bent0b0x** [comment]
In general I think the app is more organized if all of our asynchronous/network-related actions are kept in thunks (or `XXXActions.js` functions). Adding this logic to the components makes it more difficult to unit test if/when we choose to do so, and makes the component more difficult to reason about
