### ISSUE TITLE
Landing page content

### ISSUE THREAD

**Issue by jrgarou** [Paratii-Video/paratii-portal#658]
### Header Content:
What you think to use more than one video and show them randomly?
The videos info:
- Title
- Image
- URL

![image](https://user-images.githubusercontent.com/320157/40846368-ca081566-658f-11e8-8942-47fb8b198e91.png)

### Videos Content:
The videos info:
- Title
- Image
- URL

![image](https://user-images.githubusercontent.com/320157/40846714-c479c7c4-6590-11e8-86ff-30a832c8a66a.png)

**Comment by dtquandt** [comment]
https://portal.paratii.video/play/65te9Z7bXDM4
https://portal.paratii.video/play/cpApjlvwRK8O
https://portal.paratii.video/play/A9SftW9yaPcJ
https://portal.paratii.video/play/XTCgW0oToNnc
https://portal.paratii.video/play/rOHszskLtIEy
https://portal.paratii.video/play/9qMA3KhZir2Z

I propose these as the first batch of header videos.

**Comment by dtquandt** [comment]
We're also going to have to include the header videos among the ones that show up below, because there are way too few by too few authors, otherwise. This is the rest of the videos we can feature, but it might be best to limit them to two per author to avoid flooding the page with videos by one author:
RYE
https://portal.paratii.video/play/rLUx7zTeDgvz
https://portal.paratii.video/play/jLruXIOA7cWS
https://portal.paratii.video/play/AUAs3eI9PSsn
https://portal.paratii.video/play/iVj8l68TaScv
https://portal.paratii.video/play/PXOTjk3Ow6St
https://portal.paratii.video/play/D93ftQHK3OXN

AROUND THE BLOCK
https://portal.paratii.video/play/a4Dbd26pLu0X 
https://portal.paratii.video/play/dTrmfJs8r6Dk
https://portal.paratii.video/play/4ftcuLQCkvV1

O CUBO
https://portal.paratii.video/play/mF7YHwBeGqZq
https://portal.paratii.video/play/XVWXVSwMkXa8

OTHERS:
https://portal.paratii.video/play/9Jh8KlGxtRIC
https://portal.paratii.video/play/10wBsdyp4biH

I propose we use the last two from Rye, the first and third from AtB, and all the others. With the header ones, that's still 14, or 2 short of what we need for the videos below, so we should take one more from Rye and one more from AtB to fill it out.

As soon as we have more videos in (very shortly) we can refresh the list to something more varied.

**Comment by dtquandt** [comment]
An addendum:
Several videos are unstaked and thus were not on the DB dump I used, but these all work and can be used as videos in the lower part of the page. This would allow us to use only one Rye and one AtB video in our rotation:
https://portal.paratii.video/play/pNK5nsGL2WYw
https://portal.paratii.video/play/VLOLj6iVhuP8
https://portal.paratii.video/play/tJxLXRZimSn8
https://portal.paratii.video/play/TfboklBzSPKa
https://portal.paratii.video/play/WKj68pwWOm5a
https://portal.paratii.video/play/dTyzjCmg5mvc
https://portal.paratii.video/play/CDjEPRDCO1ED

**Comment by pedrocasa** [comment]
There's one thing that needs to be changed in the layout @jrgarou . There's a space with a drop shadow behind it on my design ( I created it to cause the feeling that there are more content below
![screen shot 2018-06-04 at 6 59 20 pm](https://user-images.githubusercontent.com/30123644/40944034-a61e4232-6829-11e8-8f40-a5a482154b6f.png)

**Comment by dtquandt** [comment]
![screen shot 2018-06-04 at 7 13 29 pm](https://user-images.githubusercontent.com/22087080/40945012-578ea784-682d-11e8-982d-865516410d38.png)
![screen shot 2018-06-04 at 7 03 46 pm](https://user-images.githubusercontent.com/22087080/40945013-57bc22cc-682d-11e8-8e1d-a7f5ff7f0ccf.png)
![screen shot 2018-06-04 at 7 06 19 pm](https://user-images.githubusercontent.com/22087080/40945014-57e6d2b0-682d-11e8-81aa-f9c597d19fd4.png)
![screen shot 2018-06-04 at 7 10 14 pm](https://user-images.githubusercontent.com/22087080/40945015-581173da-682d-11e8-8a77-b170dfe5045d.png)

Here are 4 screenshots of the header videos, missing only Venice and Mysterious Video - @pedrocasa should have those soon.

**Comment by jrgarou** [comment]
> There's one thing that needs to be changed in the layout @jrgarou . There's a space with a drop shadow behind it on my design ( I created it to cause the feeling that there are more content below like vimeo land page )

Fine.
But I think if we want to show to user that are more content below we need to show some content or use some element to clarify that(like an arrow ⬇️)

**Comment by dtquandt** [comment]
##Header Videos
###Video 1:
- Vento Na Janela
- https://portal.paratii.video/play/65te9Z7bXDM4
- https://user-images.githubusercontent.com/22087080/40945013-57bc22cc-682d-11e8-8e1d-a7f5ff7f0ccf.png
###Video 2:
- Johnny B. Goode
- https://portal.paratii.video/play/cpApjlvwRK8O
- https://user-images.githubusercontent.com/22087080/40945014-57e6d2b0-682d-11e8-81aa-f9c597d19fd4.png
###Video 3:
- Yunta
- https://portal.paratii.video/play/A9SftW9yaPcJ
- https://user-images.githubusercontent.com/22087080/40945015-581173da-682d-11e8-8a77-b170dfe5045d.png
###Video 4:
- A Mysterious Clip
- https://portal.paratii.video/play/XTCgW0oToNnc
- https://user-images.githubusercontent.com/22087080/40946875-42b811ac-6836-11e8-88f7-2264234d57c6.png
###Video 5:
- CHONPS | Robin & Batman
- https://portal.paratii.video/play/rOHszskLtIEy
- https://user-images.githubusercontent.com/22087080/40945012-578ea784-682d-11e8-982d-865516410d38.png
###Video 6:
- Venice Beach
- https://portal.paratii.video/play/9qMA3KhZir2Z
- https://user-images.githubusercontent.com/22087080/40946949-8cccce0e-6836-11e8-80e6-f6a18a9fc5a2.png

**Comment by jrgarou** [comment]
@dtquandt @pedrocasa 
Some images aren't full(with black space):

Vento Na Janela
https://user-images.githubusercontent.com/22087080/40945013-57bc22cc-682d-11e8-8e1d-a7f5ff7f0ccf.png

Johnny B. Goode
https://user-images.githubusercontent.com/22087080/40945014-57e6d2b0-682d-11e8-81aa-f9c597d19fd4.png

**Comment by jrgarou** [comment]
@dtquandt @pedrocasa 
The Venice Beach image have some texts at bottom:
https://user-images.githubusercontent.com/22087080/40946949-8cccce0e-6836-11e8-80e6-f6a18a9fc5a2.png

**Comment by dtquandt** [comment]
What do you need? Just a crop? What are the proportions?

**Comment by jrgarou** [comment]
@dtquandt just remove texts(or keep it if you want) and black vertical bars

**Comment by dtquandt** [comment]
https://user-images.githubusercontent.com/22087080/40949309-c848c408-6843-11e8-8c86-e0126eb29114.png

https://user-images.githubusercontent.com/22087080/40949459-970e33b8-6844-11e8-81bc-74f4ac725892.png

https://user-images.githubusercontent.com/22087080/40949310-c869ac2c-6843-11e8-8132-17a622c0e79c.png

Are these OK? I didn't keep aspect ratio for the ones I cropped.

**Comment by pedrocasa** [comment]
Sure @jrgarou. Files and links already updated 

![screen shot 2018-06-05 at 2 49 30 pm](https://user-images.githubusercontent.com/30123644/40993323-ad2da206-68cf-11e8-8103-64f3a32f7c42.png)

**Comment by dtquandt** [comment]
## Videos Content
(header videos are included, it would be nice but not critical to avoid repeating the header video below)
### Video 1:
- Vento Na Janela
- https://portal.paratii.video/play/65te9Z7bXDM4
- https://user-images.githubusercontent.com/22087080/40945013-57bc22cc-682d-11e8-8e1d-a7f5ff7f0ccf.png

### Video 2:
- Johnny B. Goode
- https://portal.paratii.video/play/cpApjlvwRK8O
- https://user-images.githubusercontent.com/22087080/40945014-57e6d2b0-682d-11e8-81aa-f9c597d19fd4.png

### Video 3:
- Yunta
- https://portal.paratii.video/play/A9SftW9yaPcJ
- https://user-images.githubusercontent.com/22087080/40945015-581173da-682d-11e8-8a77-b170dfe5045d.png

### Video 4:
- A Mysterious Clip
- https://portal.paratii.video/play/XTCgW0oToNnc
- https://user-images.githubusercontent.com/22087080/40946875-42b811ac-6836-11e8-88f7-2264234d57c6.png

### Video 5:
- CHONPS | Robin & Batman
- https://portal.paratii.video/play/rOHszskLtIEy
- https://user-images.githubusercontent.com/22087080/40945012-578ea784-682d-11e8-982d-865516410d38.png

### Video 6:
- Venice Beach
- https://portal.paratii.video/play/9qMA3KhZir2Z
- https://user-images.githubusercontent.com/22087080/40946949-8cccce0e-6836-11e8-80e6-f6a18a9fc5a2.png

### Video 7:
- O que é Algoritmo
- https://portal.paratii.video/play/D93ftQHK3OXN

### Video 8:
- Around the Block - Trailer 
- https://portal.paratii.video/play/a4Dbd26pLu0X

### Video 9:
- Todo Tempo do Mundo - Ep. 1
- https://portal.paratii.video/play/mF7YHwBeGqZq

### Video 10:
- Só Quero Fazer Falta
- https://portal.paratii.video/play/9Jh8KlGxtRIC

### Video 11:
- Vlog 1 - O começo
- https://portal.paratii.video/play/10wBsdyp4biH

### Video 12:
- Palafita Filmes Reel
- https://portal.paratii.video/play/pNK5nsGL2WYw

### Video 13:
- Comece Logo Sua HQ
- https://portal.paratii.video/play/VLOLj6iVhuP8

### Video 14:
- Hipótese do Tempo Fantasma | Beirologia
- https://portal.paratii.video/play/tJxLXRZimSn8

### Video 15:
- Degustando Whisky - Johnnie Walker Red Label
- https://portal.paratii.video/play/TfboklBzSPKa

### Video 16:
- Garage
- https://portal.paratii.video/play/WKj68pwWOm5a

### Video 17:
- Final de Semana Dourado - Rolê com Dom 
- https://portal.paratii.video/play/dTyzjCmg5mvc

### Video 18:
- Gurufim Na Mangueira
- https://portal.paratii.video/play/CDjEPRDCO1ED

**Comment by dtquandt** [comment]
Videos Content has been updated with images and the final selection.

**Comment by jellegerbrandy** [comment]
:+1:
