### ISSUE TITLE
Do not load massive thumbnails in search results and player

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#660]
👇 example of a thumbnail we are loading for search results. This is huge and takes forever to load, let's load a much smaller version 😄 

![image](https://user-images.githubusercontent.com/7697924/40862461-96517b06-65ba-11e8-997f-953aa1f10645.png)

We should also do the same for the player, as the start-screen thumbnails also take forever to load

**Comment by bent0b0x** [comment]
After a bit of digging, I think this is something we need to change on the BE. @ya7ya it looks like we are only generating `1920x1080` thumbnails (or at least that is all the db returns). Do you know how hard it would be to generate smaller sizes? 

I was just testing on production on a good connection and it took > 10 seconds for all of the search result thumbnails to load and I suspect it is because they are all very large.

**Comment by ya7ya** [comment]
yeah. I'll try to see if we can resize thumbnails on the fly to something less huge 😄

**Comment by bent0b0x** [comment]
Thanks @ya7ya ! You are the best. Let me know if/when this is done and what the FE should do to adjust 😄
