### ISSUE TITLE
Take advantage of potential new internal structure of bip39

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#662]
I have opened up [this PR](https://github.com/bitcoinjs/bip39/pull/82) in the `bip39` repo, which would give us a `90KB` reduction in bundle size. If the PR gets merged, we'll want to restructure ouf `bip39` to import directly the functions we need and no extraneous code.

- [ ] merge PR in `bip39`
- [ ] change imports in this repo
- [ ] change imports in `paratii-js`

**Comment by jellegerbrandy** [comment]
good call, @bent0b0x  - you'll need to fix the tests to have it accepted, though :-) https://travis-ci.org/bitcoinjs/bip39/jobs/387441170

**Comment by bent0b0x** [comment]
I believe those same tests are failing on `master` in that repo.

There seems to be some resistance from the `bip39` maintainers to merge in my PR, I'll see what I can do.

Regardless, in their next version they will be dropping their large language files from their main module so we will be able to not import those. That might be enough for us, but I'll try to check to see when that version will be released.
