### ISSUE TITLE
Implement design for player page in portal

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#67]

**Comment by pedrocasa** [comment]
first sketch of the video page

![00](https://user-images.githubusercontent.com/30123644/35438834-439d6a76-027f-11e8-82cc-122791f30b6e.png)

**Comment by felipegaucho** [comment]
Closing this, although the **user icon** must be taken away from the embedded player in this context (portal).

**Comment by pedrocasa** [comment]
Done in this image @felipegaucho

**Comment by jellegerbrandy** [comment]
We have this design now, we can create separate issues for particular features or problems
