### ISSUE TITLE
Revisit our color theming

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#670]
Right now we have a [theme file](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/foundations/base/Themes.js). It manages all of the colors throughout the entire app, but I would argue in a not-so-helpful way. If we want to change the color scheme of the app we'd have to evaluate every specific color in the theme file and swap it with another color. This is not ideal. In addition, this file is going to keep growing as the app grows. It is not scaleable.

**Proposed Solution**
Our theme colors should merely alias colors w/ specific names like `backgroundColor`, `textColor`, `secondaryTextColor`, `accentColor`, etc. This way we will end up w/ a manageable amount of colors and if we do things right switching themes would be fairly trivial. 

Interested to hear thoughts from @jrgarou

**Comment by jrgarou** [comment]
In the beginning, @pedrocasa and I have tried to define some color patterns(text with color X and titles with color Y with some variations, main/dark/light colors for backgrounds, etc)  but we've done a lot of changes(design and UI mostly), so I decide to do that by component for now. 
 
I totally agree with you, @bent0b0x. We need to do that, but we still defining how the things must be.

**Comment by bent0b0x** [comment]
Sounds good. Yes we'll definitely want to work with @pedrocasa on this when the time comes

**Comment by jrgarou** [comment]
Working on that in https://github.com/Paratii-Video/paratii-portal/tree/fix/ui-design

**Comment by jrgarou** [comment]
Working progress in https://github.com/Paratii-Video/paratii-portal/pull/769
