### ISSUE TITLE
visiting non-existing vid fails silently

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#672]
https://staging.paratii.video/embed/CLaG96WzOkjc

in the console, there is a warning that the ipfsHash cannot be found. 

We shoudl raise a 404 error here, probably.

**Comment by eliawk** [comment]
@jellegerbrandy it seems a different problem because this video doesn't exist:
https://staging.paratii.video/embed/xxx
and you get a 404

**Comment by jellegerbrandy** [comment]
yes, in this case it is probably a corrupt record in the database (somehow
we do not kow the ipfsHash). But tot he user, I think it should be
presented as a 404 just the same.
