### ISSUE TITLE
translations!

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#676]

**Comment by bent0b0x** [comment]
Do we know what languages we plan to support? And how we might want to get accurate translations (for languages we don’t speak natively 😊)

**Comment by jellegerbrandy** [comment]
in this first stage, it will be english and portuguese

we do not have a final lsit, but the website also has a translation in
chinese, so we could ask the same person to translate the app as well.

**Comment by bent0b0x** [comment]
I will take a first stab at this 👍

**Comment by bent0b0x** [comment]
Closing this as the PR is merged and I have created a few addl issues as follow-ups
