### ISSUE TITLE
Videos that fail to transcode are not actionable

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#682]
For a video that fails to transcode, we just leave it in the video list and the user cannot do anything with it. 

![image](https://user-images.githubusercontent.com/7697924/41008923-dc6d470c-68fb-11e8-8313-58ac77ea543b.png)

**Proposed solution(s)**
- allow user to delete from the list
- allow user to click a retry button
- do both

thoughts @felipegaucho @jellegerbrandy ?

**Comment by eliawk** [comment]
@bent0b0x actually the transcoder should automatically retry to transcode an uploaded video, if i remember correctly

**Comment by jellegerbrandy** [comment]
The transcoder does not retry, but the application does, i think.
However, if the file cannot be transcoded becuase of some internal error
(wrong type, corrupt file, file nto available, whatever), retrying will not
fix that.

We did have some logic for hiding vids on the list that are not in a
"useable state" - perhaps we simply restore that (i.e. do not show vids
that have transcodingStatus === error...)
