### ISSUE TITLE
Add more feedback indicating that video is uploading/transcoding

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#683]
Currently, we have little feedback to indicate to the user that we are actually uploading their video (once our notifications dismiss). We used to have a progress bar, but now we just show this:

![image](https://user-images.githubusercontent.com/7697924/41008961-1c2997e2-68fc-11e8-86a5-757dfdff03ee.png)

I think we should at least put the loading spinner next to this text. Thoughts @pedrocasa ?

EDIT: my transcode was taking so long that I did not notice that the grey bar was indeed still a progress bar. Perhaps we can include a spinner to make it clear upload is happening if the progress bar is stuck at 0 at the beginning (or stuck at any percentage along the way)

**Comment by jellegerbrandy** [comment]
We can also cheat a bit and have the progress bar go to 1 or 2% before anything has actually happened.

I personally agree that the feedback a bit too subtle - the "purple on grey" and the thin-ness of the progress bar makes it hard to see that it _IS_ a progress bar, and i find myself opening devtools to check if progress is happening. (@pedrocasa feel free to ignore this :-))
