### ISSUE TITLE
create Tipping UI

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#684]
Here are the designs of the tipping process. We have designed a flow that gonna be used in the embeddable player and inside the portal. 

- Hardcoded values: No room for arbitrary amounts of PTI.

- We talked about where to show the errors and rather show them all in the same place (in the password confirmation page), no notifications or extra screens. See if the flow looks good to you and if it's fine to fetch the username at the moments we propose.

- The Thank you screen has three options (two that need the name of the user). If we can have them randomly appearing would be awesome. Every tip a new experience.

- Talking about experience, it would be cool to have a coin-like SFX when the TX is confirmed (e.g.: https://www.youtube.com/watch?v=cQ5JIcDx3fg - if it's too kitschy, just ignore). 

- The U$ value is just a placeholder and shouldn't be implemented now

![tip_flow](https://user-images.githubusercontent.com/30123644/41008954-6ce12cf6-6904-11e8-9648-0e7f2e24a66b.png)

Adobe prototype link
https://xd.adobe.com/view/c34704c3-94b6-4504-aac2-44e2c19c8ced

- [ ] Add tests!

**Comment by bent0b0x** [comment]
I love it! For the thank you screen I am a fan of the second option

**Comment by felipegaucho** [comment]
Could also have a small tweet button on the thank you screen (tweets the video + "I just tipped + the thank you sentence".

**Comment by eliawk** [comment]
@pedrocasa super nice!

**Comment by jellegerbrandy** [comment]
Very cool. Not sure about the kitchy kedching effect :-)

(ben: if I understand pedro correctly, the idea is not that we choose a
thank you screen, but we show on of these three randomly...)

**Comment by pedrocasa** [comment]
@bent0b0x  here are the specs link and the assets to develop it.

specs https://xd.adobe.com/spec/a4036521-bcd4-454b-8f9d-d0093b02c4d6
assets https://we.tl/U84fDeZ1Nj

**Comment by bent0b0x** [comment]
@felipegaucho @pedrocasa when do we show the "tip" prompt/button? Right when the video starts? I think that seems spammy and maybe it's good to wait a little?

Let me know your thoughts!

**Comment by bent0b0x** [comment]
Another question: where has this symbol come from?

![image](https://user-images.githubusercontent.com/7697924/41326672-0b7eb2a0-6e8e-11e8-8c0a-67b68c1fd2e5.png)

Is this a standard way of representing USD? It is not one I have seen

**Comment by jellegerbrandy** [comment]
I had not noticed that but: We are **not** going to put a US dollar value for the PTI on the app. We cannot (adn do not want to) make any claims or promises about the PTI price.

**Comment by pedrocasa** [comment]
@bent0b0x  Leave it without de USD for now

**Comment by felipegaucho** [comment]
Being a bit contrarian: doesn't showing "0,00 USD" make it clearer (or more clear) that there's no real value in that? @jellegerbrandy

**Comment by jellegerbrandy** [comment]
yeah, that I like :-)

**Comment by bent0b0x** [comment]
@felipegaucho @pedrocasa we discussed this but I don't think we ever documented it, so want to make sure. Do we ask for a tip only if the user has already secured their wallet?

If the user has an account and it needs to be decrypted, do we ask them to secure once they click on the tip button? The only thing I see weird about that is the tip flow will ask them for their password again, which will seem annoying. If the user has just secured we can decide to not ask for the password again when tipping.

Let me know what you think; right now I'm building it so the button only shows if the wallet is secured, but this can be changed.

**Comment by felipegaucho** [comment]
I'm up for showing the button for anyone, after 3s of video playing or whatever, to "secured" and anonymous users alike. If secured, have to type password to tip. If just secured (like seconds, can we do that?), no need to retype the password you just made up, just for the tip. But if we need to ask it again, fine for me too.

**Comment by bent0b0x** [comment]
The PR is good to go; I've added a todo on this issue to add tests, as that is not yet in this PR

**Comment by jellegerbrandy** [comment]
PR is merged, closing this, tracking any new further tasks on #749 and #765
