### ISSUE TITLE
Render translations that contain html content

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#689]
Translating [this](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/components/structures/footer/MainFooter.js#L57-L74) is not straightforward:

```javascript
v0.0.1: This is a beta tool! We &hearts; to get feedback on Telegram{' '}
          <Anchor
            anchor
            href="https://t.me/paratiivideo"
            target="_blank"
            underline
          >
            BR
          </Anchor>{' '}
          or{' '}
          <Anchor
            anchor
            href="https://t.me/joinchat/EWZMBQ9mnqJ1--NKHpyF8A"
            target="_blank"
            underline
          >
            EN
          </Anchor>
```

It contains JSX, which our translator cannot handle. We need to somehow pre-render the JSX into raw strings that can be passed as options to the entire translate-able string. We can do this with react dom's `renderToString`, but we'll also need to pass the `styled-components` theme to the links/elements or else rendering will not work 😄 

https://www.styled-components.com/docs/advanced#server-side-rendering

**Comment by bent0b0x** [comment]
We spoke on the call but: 
- there are a few cases, not an overwhelming amount
- We cannot just concat multiple translations because that assumes that the order of phrases will be identical across all languages.

For now we should probably just reword these translations and then revisit a complete solution for this.

**Comment by jellegerbrandy** [comment]
Agreed. This has low priority for now

**Comment by bent0b0x** [comment]
It has been solved
