### ISSUE TITLE
🎨 Design.Portal UI KIT & UX  [definite thread]

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#71]
Issue to talk about the general Design of the portal

- Here are the pages of the portal and all the flow that we have
Last update 02/21/2018

https://xd.adobe.com/view/ac964a03-32b8-40ed-a868-4a849aecd855/screen/08089d32-4bc8-439d-9e61-761165c62d48/P-06

If need to talk about something very specific try to use the Adobe tool 

-  Here it is the individual elements of the UI 
Last update 02/21/2018

Adobe Design specs (free account needed to open it)
https://xd.adobe.com/spec/c5439492-f16e-445d-ae25-9f202718f5b6

**Comment by eliawk** [comment]
@pedrocasa this is very sexy!

**Comment by felipegaucho** [comment]
Application of the UI Kit to version 0.0.1 of the portal: https://xd.adobe.com/view/ac964a03-32b8-40ed-a868-4a849aecd855/screen/08089d32-4bc8-439d-9e61-761165c62d48/P-06

Last update: 02.22.2018  11:56am BRT

**Comment by pedrocasa** [comment]
Possible changes on the upload/edit process 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/30123644/37785804-d89a26fc-2dd9-11e8-946a-dde197b4f95f.gif
