### ISSUE TITLE
upload status is not updated to "transcoding"

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#712]
the console says that it is "transcoding", but the status in the list says "uploading":

![image](https://user-images.githubusercontent.com/1306173/41341401-e9c65b6a-6ef9-11e8-8dce-636527bd2581.png)

**Comment by jrgarou** [comment]
Now the `statusMessage`is changed to _'Transcoding your video'_ when _transcodingStatus_ is requested

https://github.com/Paratii-Video/paratii-portal/blob/7201dae9924e6747a628927cc768def6fbf3803a/src/scripts/components/UploadListItem.js#L367-L368

**Comment by bent0b0x** [comment]
Can we translate all of these? 😬
