### ISSUE TITLE
Password reset is not working

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#719]
(On staging - Firefox Quantum)

Reproducing:
1. Have an account
2. When prompted for password, select "forgot password"
3. Enter mnemonic phrase
4. Enter new password
5. On pressing continue, nothing happens.

**Comment by eliawk** [comment]
ReferenceError: event is not defined[Ulteriori informazioni]
bundle.js%20line%201%20%3E%20eval:157:1
__handleKeydown__REACT_HOT_LOADER__
Modal.js:161:4
Modal/_this.handleKeydown
