### ISSUE TITLE
`npm run server:dev` should exit if deployContracts fails

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#72]
In particular, if you have no blockchain running, and start `server:dev`, the server will be stareted but hte contracts will not be deployed, an dyou'll have  abroken app

**Comment by bent0b0x** [comment]
@jellegerbrandy took a (very quick) stab at this, but think there _might_ be something w/ now `paratii-lib` handles errors that prevents us from appropriately responding to them.

I would expect that we could `.catch` and error from `deployContracts`, but I do not think that is the case. See [this branch comparison](https://github.com/Paratii-Video/paratii-portal/compare/72-dev-error-handling). 

Thoughts?

**Comment by jellegerbrandy** [comment]
I think you may be right. I've opened in issue on https://github.com/Paratii-Video/paratii-lib/issues/87

**Comment by jellegerbrandy** [comment]
Ok, that issue is now closed so we can do this
