### ISSUE TITLE
make it clearer that we are on a private net

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#723]
comment from chris:

```When I finished my signup, and it told me I have 25 PTI, but there's no sign of this in Etherscan for the account (mainnet, rinkeby, ropsten, kovan) - are these tokens on some kind of private testnet?```

**Comment by jellegerbrandy** [comment]
Hey @pedrocasa , any ideas on this?

**Comment by felipegaucho** [comment]
Done with the new header/bar.
