### ISSUE TITLE
Refactor <Button /> component

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#737]
There are a few things we should rethink about `Button.js`

- [ ] it exports raw css styles used by other components
- [ ] it maps properties like `props.white` to `Colors.white`, when in fact I think we should just pass in colors directly (there is no point to this abstraction IMO)
- [ ] perhaps the button is not versatile enough to work for all of our use cases. We should work w/ @pedrocasa to outline the different kinds of re-usable buttons we want and write components for all of them, so that we can easily plug them in anywhere we need

cc @jrgarou, let's continue our discussion here (and feel free to bring up any other points)!

**Comment by jrgarou** [comment]
Great, @bent0b0x 

> it maps properties like props.white to Colors.white, when in fact I think we should just pass in colors directly (there is no point to this abstraction IMO)

I disagree, but we must define the colors by states: something pretty basic like _normal_, _error_, _success_, _warning_, _disabled_, etc. The theme defines these colors. 
And share these styles(`color` ou `background-color`).

## Styles
There are two kinds of buttons currently, the button with the colored background and text buttons. We could create this two kind of buttons. I think it's enough.
#### Button
`<Button />`
It's uppercase, have background-color(share this style), dropshadow(? @pedrocasa can confirm), text center(vertical and horizontal), border-radius(share the radius value, perhaps UIConstans). Its color should _white_, and its background-color should be contrast with that.

#### TextButton
`<TextButton />`
It's uppercase, have colored text(share this style), dropshadow(? @pedrocasa can confirm)

### Extra: 
#### TextButton link
This is about the `<a>` or `<button>` inside a text or not. It's, basically, the TextButton without uppercase, and perhaps an _underline_ `text-decoration`

**Comment by bent0b0x** [comment]
This is great, thanks @pedrocasa !

**Comment by jrgarou** [comment]
Working on that in https://github.com/Paratii-Video/paratii-portal/tree/fix/ui-design
