### ISSUE TITLE
Build and deploy very simple webapp allowing us to trigger translation pushes to github

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#742]
POEditor allows us to push translations to a github branch via a webhook. Members of the Paratii organization can also do this via the POEditor UI, but it would be great for translators to be able to push their translations to `dev` when they are complete.

To do this, we need to hit this webhook:

https://poeditor.com/api/webhooks/github?api_token=TOKEN&id_project=192597&language=pt-br&operation=export_terms_and_translations

My plan is to deploy a very very simple webapp on heroku free that basically just contains a button that can be clicked to trigger this request. It needs to be deployed because we cannot pass around the api token; we need to obfuscate it by proxying the request to a simple BE server.

**Comment by bent0b0x** [comment]
Here it is: https://paratii-translations-ui.herokuapp.com/

**Comment by bent0b0x** [comment]
Basics are working; I've shut the app down for now so that I can make the following changes:

- [ ] do not commit directly to `dev`
- [ ] commit instead to a translations branch
- [ ] open a PR (if none exists) every time we commit to said translations branch

**Comment by bent0b0x** [comment]
https://developer.github.com/v3/git/refs/#create-a-reference

https://developer.github.com/v3/repos/merging/

https://developer.github.com/v3/pulls/#create-a-pull-request

- request comes in
- create translations branch (if not exist)
- merge `dev` into branch
- create PR into `dev`

**Comment by felipegaucho** [comment]
@bent0b0x how much work would it be to make the above flow work?
I didn't get to see the app functioning.

**Comment by bent0b0x** [comment]
Too much work, IMO 😄
