### ISSUE TITLE
How to acess the video-in-the-TCR pages

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#744]
To be more clear in this issue I'm going to explain two terms that I'm going to use. 

video-page = Regular page of a video, there's no voting on it. You just go there to watch and have fun.

video-in-the-TCR = It's the page where you can vote on the permanency of some content

-------

### The challenge that we're facing right now is this:

We are developing the video-in-the-TCR page but we do not have a way to access it on our platform. The original idea was to have a list of all videos but due to the complexity of it would take a considerate amount of time to develop. 

So in order to have a TCR usable asap, we've been discussing what would be a temporary solution to access those pages. On the last calls, we've talked about creating an input-URL card where the user can paste the video-page URL and them go to the video-in-the-TCR related to it. It would solve our problem but it would also create a couple of UX issues that could worsen the usability.

- No one would memorize the URL address. Even though you could find the address in your browser's history, users would repeatedly go back to the video-page to copy the URL instead.

- Afaik videos that are currently on vote/reveal period are not available on the platform. This would result on only users that have the address saved on the browser accessing it.

To solve these challenges the team created a way of going to the video-in-the-TCR with less effort and not depending on the actual state of the voting process to access it.

It's a small change on the video-page that will allow the users to go directly to the video-in-the-TCR page that is related to it. The previous video-page designs (https://xd.adobe.com/view/0e6fd094-9680-4f4d-b43f-8a1e9875fd06)  got a related content box but as we do not have the amount of content necessary to make this in a more complete way let's forget about it for now and apply those "curate this video" boxes that are on the images above.

1- This is the video-page if the video is whitelisted ( no one has challenged it yet)

![15151](https://user-images.githubusercontent.com/30123644/41937453-b2756260-7966-11e8-9e6b-8116532c7650.png)

2- This is the video-page if the video is on voting/reveal period. ( there are two ways to go to the video-in-the-TCR page: button in the center of the video frame/ button on the modular box)

![flow-04 16](https://user-images.githubusercontent.com/30123644/41934255-ade59274-795c-11e8-977c-8b74250c2199.png)

3- This is the video-page if the video has been removed from our platform. ( there are two ways to go to the video-in-the-TCR page: button in the center of the video frame/ button on the modular box)

![flow-04 17](https://user-images.githubusercontent.com/30123644/41934263-b55c19ec-795c-11e8-8dbe-21637d647055.png)

- This solution is temporary and is going to be redesigned when we are able to develop the TCR list.

- This may require more effort on the front-end of the video-page of our platform. This will be the opportunity to focus more on a page that has already been re-designed (video-page) but not yet totally implemented.

**Comment by jellegerbrandy** [comment]
:+1:

just a small remark: as it looks now, the videos *will* be available during the challenge process, and only be removed after (and if) they loose the challenge

**Comment by eliawk** [comment]
> video-page = Regular page of a video, there's no voting on it. You just go there to watch and have fun.

> video-in-the-TCR = It's the page where you can vote on the permanency of some content

this make sense to have two different page??

**Comment by pedrocasa** [comment]
"doesn't make sense to have two different page??"

for now: not so much 
for the future: Yes totally, ( most of our users are not going to understand the TCR, it's probably not a good an idea to fell them if a lot of information that most of them are not gonna be interested)
