### ISSUE TITLE
Show the number of views

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#747]
Most of the designs have this "number-of-views" feature that needs to be developed (video-page, my-videos, video-in-the-TCR ...)

![screen shot 2018-06-26 at 4 32 38 pm](https://user-images.githubusercontent.com/30123644/41934974-91ae931a-795e-11e8-862c-3809a4468b34.png)

**Comment by felipegaucho** [comment]
@pedrocasa this is a duplicate of https://github.com/Paratii-Video/paratii-portal/issues/612
