### ISSUE TITLE
Balance needs to be updated

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#756]
We used to do polling here to update the balance. I'm not clear on what the status of that is, but apparently it is not working :-)

reproduce in dev:

* run the portal, log in, look at your balance 
* run `node dev/faucet.js` to send yourself some PTI
* see that your balacne is not updated [<- this is not good]
* reload the page, login again, see updated balance

**Comment by eliawk** [comment]
@jelle after the faucet my balance has been updated..so it seems working!
