### ISSUE TITLE
My video Corrections 

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#762]
Changes that need to be made on my videos page

![screen shot 2018-07-03 at 7 05 55 pm](https://user-images.githubusercontent.com/30123644/42246769-379a7092-7ef4-11e8-9b0e-32d6489cf686.png)

- [ ] Separete Publish/Unpublish menu  (link: https://xd.adobe.com/view/2f69ed6b-d99d-4c99-bc2a-aa226993dd48) 

- [x] the menu should always be on top of the page

- [ ]  Apply "search files" (upload) button

- [x] The color of the menu needs to be changed for altBlack

Filters are not the main priority of this issue ( it will require the creation of a down menu that we don't have yet)

- [x] We need the edit link working 

- [ ] We should probably show how much you staked, I think, like on the uploads page 

- [ ] On the current My videos page the cards behind the videos are missing 

![screen shot 2018-07-19 at 15 07 02](https://user-images.githubusercontent.com/30123644/42961548-6d9137f8-8b65-11e8-8616-a7fd38e83f0b.png)

- [x] We need to change the color of this button (image below) to Colors.grayLight in the first texts and in the '' +'' icon /// and Colors.gray in the text that is in parentheses

**Comment by jellegerbrandy** [comment]
(edit; added 2 items to the list)

**Comment by pedrocasa** [comment]
New adjusts @jrgarou

**Comment by jrgarou** [comment]
@pedrocasa @jellegerbrandy 

>  Apply "search files" (upload) button

This already has been applied.


> We should probably show how much you staked, I think, like on the uploads page

Where?


>  On the current, My videos page the cards behind the videos are missing

Fixing soon(on `feat/tcr-interface` is done)

> - We need to change the color of this button (image below) to Colors.grayLight in the first texts and in the '' +'' icon /// and Colors.gray in the text that is in parentheses

I don't get it. There's no image.

**Comment by jellegerbrandy** [comment]
status of this, @pedrocasa , @jrgarou ?

**Comment by pedrocasa** [comment]
done
