### ISSUE TITLE
Implement "Cancel" button on the upload page

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#768]
We need a way to cancel the upload for cases that users have chosen the wrong video. In the original design there's a cancel button next to the publish button.

**Comment by bent0b0x** [comment]
@pedrocasa can you post the design for the cancel button?

@ya7ya or @jellegerbrandy is there an api available in `paratii-js` to cancel an upload?

**Comment by jellegerbrandy** [comment]
No there is no such API, but there probably should be:
https://github.com/Paratii-Video/paratii-js/issues/298

We can already implement the UX without this function (i.e. create teh
button, remove the item from the list, etc)

**Comment by pedrocasa** [comment]
Just a simple button next to the publish, 

![web 1920 1](https://user-images.githubusercontent.com/30123644/42513936-932a9902-842e-11e8-98c7-dccfc9a9239b.png)

Our upload page is not 100% looking like the original design( https://xd.adobe.com/view/8754f846-e4ea-4170-803b-9b5b8b4b872f/screen/52349cc8-1239-4851-9790-64ad7f76fdf0/upload-1920-1 ), but for now, let's just add this cancel button

**Comment by jellegerbrandy** [comment]
note that the paratii-js functionality is there now

**Comment by felipegaucho** [comment]
@jrgarou this is a small UI thing now that it's doable on paratii-js: https://github.com/Paratii-Video/paratii-js/issues/298
We can keep it on radar.
