### ISSUE TITLE
Unpublished videos are being published

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#779]
Videos that I did not give stake are being published and going to the page of my videos.

This is happening on both  Staging and Production

![screen shot 2018-07-11 at 10 30 35](https://user-images.githubusercontent.com/30123644/42575124-3623440c-84f6-11e8-9d0f-2a7809e9d4ea.png)

![screen shot 2018-07-11 at 10 30 22](https://user-images.githubusercontent.com/30123644/42575088-2d0e02d0-84f6-11e8-9cce-248141eaeb42.png)

![screen shot 2018-07-11 at 12 17 25](https://user-images.githubusercontent.com/30123644/42582010-7114aa48-8504-11e8-913f-2a4ed3683d05.png)

**Comment by bent0b0x** [comment]
IMO unpublished videos should appear on my videos and we should allow you to publish from there. 

But we should update our logic to not allow playing of unpublished videos

**Comment by jrgarou** [comment]
I've removed the link from unpublished videos and show the correct status - only _publish_ and _unpublish_
The commit/branch: https://github.com/Paratii-Video/paratii-portal/commit/fe324199620dc886f859c6d423422d7a352c2054


> IMO unpublished videos should appear on my videos and we should allow you to publish from there.

There's no button to publish the video, but I think it's a good idea, @bent0b0x 
What you think, @pedrocasa? 


--

![image](https://user-images.githubusercontent.com/320157/42587240-77280270-8510-11e8-8256-88ce6a67de7f.png)

**Comment by pedrocasa** [comment]
OK, 

the solution, for now, use the status as ''published'' or ''unpublished''

If the user clicks on the published ones he will go to the video page and if he clicks on the unpublished ones a modal ( same as the one that appears on the upload process) would appear.
  
![web 1920 22](https://user-images.githubusercontent.com/30123644/42600318-3e857628-8538-11e8-8bb8-f72444af60bb.png)

![web 1920 23](https://user-images.githubusercontent.com/30123644/42600320-4018e722-8538-11e8-8e45-09ec4103c29b.png)



I still think that showing the published and unpublished videos may be difficult for (especially when add more subcategories such as Whitelisted, challenged ... etc). but for now, this solution may handle it
