### ISSUE TITLE
Need util to send PTI in integration tests

### ISSUE THREAD

**Issue by bent0b0x** [Paratii-Video/paratii-portal#782]
Right now if we want to test functionality that requires PTI we do not have a nice util to make this simple. 

For example, this is required to write [integration tests for tipping](https://github.com/Paratii-Video/paratii-portal/issues/738), as most of the core of the tipping functionality requires PTI.

**Comment by bent0b0x** [comment]
@jellegerbrandy would you be able to assist with this?

A `webdriver.io` command that we could run to set the user's PTI balance would be great, but if we cannot do that a util to just add (and then maybe even detract?) balance works.

I tried to wire something up but failed, due to lack of understanding.

**Comment by jellegerbrandy** [comment]
Hey ben, so this is not something i would do in the browser, but simply diretly in the test code. So it works like this (and probably we are using that pattern already in some tests):

* setupdevenv depoys to pti contract, and the default account 0xCbe4f07b343171ac37055B25a5266f48f6945b7d gets all the pti
* if you want to send some pti to some account 0x12345, you can do it like this (pesudocode, not tested):

```
const testSettings = thoseSettingsThatAreUsedInSetupDevEnvThatUse0xCbe...
const paratiiFor0xCbe - new Paratii(testSettings)
await paratiiFor0xCBe.eth.transfer(2e18, 'PTI')
```
*

**Comment by jellegerbrandy** [comment]
so to answer there is no need to set the account on the paratii object: we can use different instances of paratii  instead
