### ISSUE TITLE
implement the "clock" counter

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#786]
this is about the time counter that shows how much time is left

**Comment by jellegerbrandy** [comment]
@pedrocasa , would you be so kind to link to the xd file here?

**Comment by pedrocasa** [comment]
sure!!!!
prototype
https://xd.adobe.com/view/a73720ec-b992-43d4-b949-d7be75379fda/
specs
https://xd.adobe.com/spec/6b7e78bb-2533-4257-8ee7-06a22d87d7aa/

We can simplify it if you want Jelle
