### ISSUE TITLE
Where to show the sidebar(UserNav) if max-width: 1440px

### ISSUE THREAD

**Issue by jrgarou** [Paratii-Video/paratii-portal#790]
The `UserNav` is accessible by the avatar only, and this is not good.
![openusernav](https://user-images.githubusercontent.com/320157/42967346-53f11334-8b76-11e8-9d86-eedc3fecfca9.gif)

### Some options

1. We could put a button(icon? text? where?) to toggle the `UserNav`

2. We could create those same links(**two**) on `MainNavigation` and just shows them when reaches our breakpoint(`max-width: 1440px`). 

![image](https://user-images.githubusercontent.com/320157/42967490-c7913b20-8b76-11e8-9b66-a568d96c4c77.png)

This option brings a question: is the sidebar really necessary? 
The top header works good when `min-width: 1441px`(above our breakpoint)
![image](https://user-images.githubusercontent.com/320157/42967933-316586d6-8b78-11e8-80a0-644408d99601.png).

We could put this informations on some page, like `/profile`  and/or `/my-videos`
![image](https://user-images.githubusercontent.com/320157/42968176-e8837e18-8b78-11e8-99b4-d2b8de8f49c8.png)

What you think, guys?

**Comment by pedrocasa** [comment]
This option is the best one

''2- We could create those same links(two) on MainNavigation and just shows them when reaches our breakpoint(max-width: 1440px).'' ( im gonna design it now )

But I do think the sidebar is really important for future interactions, right now it doesn't have many buttons on it but it will be a necessary tool soon.  

''We could put this information on some page, like'' I think this info is really important to our users and hide it in a specific page may be not such a good idea.

**Comment by jellegerbrandy** [comment]
@jrgarou @pedrocasa what is the status on this? Can I close it?

**Comment by jrgarou** [comment]
working on it, @jellegerbrandy 
We've removed the UserNav on mobile and put its items on main nav. I'll commit soon
