### ISSUE TITLE
Rework Portal presentation to host AtB and focus on crypto

### ISSUE THREAD

**Issue by dtquandt** [Paratii-Video/paratii-portal#793]
New copy and design work is required to make the portal more like Netflix and less like Youtube, while also focusing on quality Crypto content. @pedrocasa and I are working on it, will post updates here.

**Comment by dtquandt** [comment]
First mockups I sent to Pedro for reference:
![capture](https://user-images.githubusercontent.com/22087080/43533654-b42ba42a-958b-11e8-974c-7fd10610f81f.PNG)
![capture2](https://user-images.githubusercontent.com/22087080/43533655-b44c4072-958b-11e8-827e-760cc215bb58.PNG)

**Comment by pedrocasa** [comment]
https://adobeid-na1.services.adobe.com/ims/jump/1533251024873_0208509e-c9db-4339-939f-190eac8f6f44_ue1

**Comment by pedrocasa** [comment]
@dtquandt Whenever it's possible can u help me on the translation of it

**Comment by jrgarou** [comment]
I can't access the `.xd`

![image](https://user-images.githubusercontent.com/320157/43615859-14509be4-9690-11e8-934a-893292839950.png)

**Comment by pedrocasa** [comment]
wtf?  well try this one https://xd.adobe.com/view/4cc7705e-2798-4ba8-4758-05ae35468473-3af6/

**Comment by jrgarou** [comment]
> well try this one https://xd.adobe.com/view/4cc7705e-2798-4ba8-4758-05ae35468473-3af6/
@pedrocasa it's beautiful 💞

I just think we should avoid the thumbs arrows. Avoid new and complex elements is helpful for fast development, and maybe(@dtquandt and @felipegaucho should know better) we ain't got much content for this.

We could use a "load more" button, to load more thumbs below the first content. Or even a "see more" button and create pages for those categories(or a better name): `category/crypto`,  `category/developers`, etc.


![image](https://user-images.githubusercontent.com/320157/43652910-e9013790-971c-11e8-8709-4ed0d02643c3.png)

**Comment by felipegaucho** [comment]
Closing this in favour of https://github.com/Paratii-Video/paratii-portal/issues/796 , where @pedrocasa should drop the designs.

I'm listing content @jrgarou , we'll get to 12-15 of each category at least.

I'm on board with category/documentaries - @Lupape, @pedrocasa and I have come up with a solution that will allow us to have this w/out any new pages. We call it "special search results". Pedro will share it in the appropriate place!
