### ISSUE TITLE
Implement categories on the landing page

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#796]
- Header section for episodical content (ATB).

- 6 categories:
  - 1- 🎥Documentaries
  - 2- 🎪Community Events
  - 3- 🔨Network builders
  - 4- 🎓Educational
  - 5- 💡Opinion makers
  - 6- 🐕World-class memes

- Criteria for acceptance:
   - Content that educates, and doesn't spread misinformation.
   - Contents that encourages participation in the crypto community. 
   - Content that provides some new, original contribution, even if it is a remix of previous material.
   - It must not target individuals for harassment or bullying.

@pedrocasa can you post the assets below? Notice I changes names of categories slightly. And if any of the emojis don't work across systems, just ignore.

**Comment by pedrocasa** [comment]
Here is some material that the communication team has suggested us to use. (we still need to check the copyrights of it).

Documentaries

-  Banking on Bitcoin (Netflix) 
- The Pirate Bay - Away from Keyboard  (https://www.youtube.com/watch?v=A0HcPlYEkzc&ab_channel=DocumentaryStorm)
- The Blockchain and us (https://www.youtube.com/watch?v=2iF73cybTBs&ab_channel=ManuelStagars)
- The Rise and Rise of Bitcoin (https://www.youtube.com/watch?v=IMJmd_tNhlM&ab_channel=BobbyLewisDanielDannett)
- The Bitcoin Gospel (https://www.youtube.com/watch?v=8zKuoqZLyKg&ab_channel=vprodocumentary)
- The Bitcoin Phenomenon (https://www.youtube.com/watch?v=hv4I99f_BoU&ab_channel=HowerJohnson)

Interviews

1- Living, Breathing, & Betting on Bitcoin 
2- The new open-source economics

**Comment by pedrocasa** [comment]
Proto: https://xd.adobe.com/view/4cc7705e-2798-4ba8-4758-05ae35468473-3af6/
specs: https://xd.adobe.com/spec/e7fb2c2b-fa26-4034-4409-39ed2b915427-91ca/

**Comment by pedrocasa** [comment]
@felipegaucho  is there a problem if we use ''ep'' instead of ''episode'' when it's locked?  (it's not easy to fit it all together on mobile after adding the icon )

![screen shot 2018-08-17 at 18 46 16](https://user-images.githubusercontent.com/30123644/44290457-2e6fe000-a24f-11e8-8f88-e8eeb373691d.png)

**Comment by felipegaucho** [comment]
@pedrocasa 
No problem at all if
- the spacing between the lock icons and "Ep.." is consistent;
- "Ep" -> "Ep."

**Comment by pedrocasa** [comment]
![screen shot 2018-08-21 at 13 06 25](https://user-images.githubusercontent.com/30123644/44414252-b4d43c80-a543-11e8-898c-b47326adcc03.png)
![screen shot 2018-08-21 at 13 06 39](https://user-images.githubusercontent.com/30123644/44414255-b69e0000-a543-11e8-8932-b21d3557759e.png) 


Let's use full box buttons for all the episodes that are being available (To fit well on every device let's use Ep. even for episodes that are already available.)

**Comment by pedrocasa** [comment]
@jrgarou 

Just two small corrections

- The '' documentaries category'' is the first one 


![screen shot 2018-08-24 at 16 12 09](https://user-images.githubusercontent.com/30123644/44603254-81e6ae80-a7b8-11e8-9d71-30ad28d75792.png)


- The ''🐕  World-class memes'' category is missing

**Comment by pedrocasa** [comment]
Ok, 

now we just need to upgrade these new buttons (ep.1) (ep.2) for I close this issue

**Comment by felipegaucho** [comment]
@pedrocasa the original issue is resolved 🎉. Please coordinate implementation (and if needed a new issue) for the episodes thing, if necessary.
