### ISSUE TITLE
[VOTE] Name for the portal web app  - options (10 AUG)

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-portal#798]
- Motivation: having an own name for the app at portal.paratii.video (rather than the "portal" at the namespace, or "paratii" at the interface's top left) helps separate the product from the rest that Paratii represents. it can also help market the product itself better.
- Format: newname.paratii.video. 
- You can also vote against changing how things are!

- Options (feel free to add):
   - 1) BetFlix
   - 2) Grab 
   - 3) Mirror
   - 4) VideoLab
   - 5) AfterAds
   - 6) Cryptoscope
   - 7) Monet
   - 8) VideoScout
   - 9) Cure
   - 10) Scavenger
   - 11) WebThreep
   - 12) CryptoHub

❓ Please leave your vote below, if possible, until the end of the day on AUG 10th! 🙏

**Comment by jellegerbrandy** [comment]
I'm conservatively voting for (d). 
(but what does "webthreep" mean?)

**Comment by bent0b0x** [comment]
(l) or (d)

**Comment by jrgarou** [comment]
d. VideoLab
or
m. Lab _(lab.paratii.video)_

**Comment by felipegaucho** [comment]
WebThreep is obviously a journey down the rabbit hole of web3 @jellegerbrandy

**Comment by lupape** [comment]
d. VideoLab
or
m. Lab

**Comment by pedrocasa** [comment]
İ.

Videolab sounds toooooo generic

**Comment by geckoslair** [comment]
g Monet

**Comment by felipegaucho** [comment]
Lab.paratii.video won (w/ no visible name change on interface).

@jellegerbrandy , how easy it is to set that (& redirect portal.paratii.video)?
