### ISSUE TITLE
should throw a 404 error if a video is not found

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#80]
e.g. on http://127.0.0.1:8080/play/thisdoesnotexist

We probably want a generic 404 error page...

**Comment by eliawk** [comment]
@jellegerbrandy i've a created a generic 404 page. but it doesn't work with:
`/play/:videoid`
because the **router** couldn't know if the id is correct.
we need to:
aks paratii.db -> get error back id the video doesn't exist, i guess..

**Comment by jellegerbrandy** [comment]
A pattern that I've seen in other frameworks is that you throw a "NotFound" error anywhere in the code, and it will return a 404 response. That is very convenient, but I'm not sure if something like that exists (or is possible) in React.

**Comment by jellegerbrandy** [comment]
Actualy, thinking about it, getting the video information in the router is fine as well, and much more straightforward. As long as we are not getting it twice...

**Comment by eliawk** [comment]
```
{
  "state": {
    "selectedVideo": {
      "description": "",
      "id": "foo",
      "ipfsData": "QmeMW3GYntHCGC82jNU4yvKzSfiMkJZcVTozhWHNUjhq3g",
      "ipfsHash": "QmQP5SJzEBKy1uAGASDfEPqeFJ3HUbEp4eZzxvTLdZZYwB",
      "owner": "0xa99dBd162ad5E1601E8d8B20703e5A3bA5c00Be7",
      "price": "0",
      "thumbnailUrl": "",
      "title": "",
      "url": ""
    },
    "user": {
      "name": "John Doe",
      "isLoggingIn": false,
      "keepUrl": true
    },
    "uploads": {}
  }
}
```

i can use `selectedVideo`

**Comment by jellegerbrandy** [comment]
no you can't, because selected video will be set on the basis of the :id in
the URL :-)

**Comment by bent0b0x** [comment]
My understanding is that we get the video id from the route, and then dispatch an action to go fetch the video. From there, this is how i think it should work:

- we have a piece of our `selectedVideo` state that indicates `fetchRequestStatus`, or something. When we first dispatch the fetch video request, this gets set to `'REQUEST_STARTED'` (👈  which should be in a constant file somewhere). Then, if the request succeeds we populate the video properties in state and also set `fetchRequestStatus` to `'REQUEST_SUCCEEDED'`. However, if it fails, we set the `fetchRequestStatus` to `NOT_FOUND`.  Then we also have a selector like `getIsVideoNotFound` that returns true if our `fetchRequestStatus === 'NOT_FOUND'`. Our component can take in a prop based on this selector and redirect to a 404 page (or just render a 404 message) if it is `true`. How does that sound?

**Comment by eliawk** [comment]
now there is ste `fetchStatus` in the state, so we can manage in the frontend
