### ISSUE TITLE
Change the copy of the login flow 

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#801]
Changes that need to be done on the text:
--
### First  modal

Title:

- Ready to sign up?

Subtitle

- It only takes 3 steps.

Left button

- I ALREADY HAVE AN ACCOUNT

Right button

- SIGN UP

### Second Modal

Title:

- Create a password

Subtitle

- Make it 8 characters or longer. Include at least 1 uppercase letter and 1 number.

First Input

- Password

### Third Modal

Subtitle

- (warning icon) It’s the only proof that you own this account. Keep it secret. Keep it safe. 

Left Button

- GO BACK

### Forth modal

Subtitle

- This is how you will be known on the Paratii network.

---

prototype: https://xd.adobe.com/view/e729d58b-fc97-4c6a-9ab0-93a09c0e20b3/
db: dro

specs: https://xd.adobe.com/spec/94aaada0-b675-4b5e-bce4-da9bdca8f6cb/

**Comment by felipegaucho** [comment]
Done!
