### ISSUE TITLE
Change ''Episodes'' for ''Ep.'' on the main  showcase of the Lab

### ISSUE THREAD

**Issue by pedrocasa** [Paratii-Video/paratii-portal#812]
We need to update the buttons of the main showcase of the lab.

- We are not gonna use ''episode X'' instead of it we will use ''Ep. X''

- Episodes that are available will be inside a button container.

- Episodes that are not available should have a lock next to it.

![44414255-b69e0000-a543-11e8-8932-b21d3557759e](https://user-images.githubusercontent.com/30123644/45002123-d9033500-afa9-11e8-828c-9a76b52cdd6a.png)

![44414252-b4d43c80-a543-11e8-898c-b47326adcc03](https://user-images.githubusercontent.com/30123644/45002133-eae4d800-afa9-11e8-82a8-922a5417c2c7.png)

**Comment by jrgarou** [comment]
@pedrocasa by default all buttons have the uppercase value

**Comment by felipegaucho** [comment]
It's done, good on ya @jrgarou and @pedrocasa !
