### ISSUE TITLE
Reconsider state definition

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-portal#94]
[copying some of @bent0b0x comments here:]

1. **SEE EDIT BELOW** In the redux store, somewhere, store our entire list of `videos`. These can be already uploaded videos, videos that are being uploaded, etc. These different kinds of videos do not necessarily have to be collocated, but they must all be available in the store. 
2. Create a new piece of state `editingVideoId`. When we are not editing a video, this is `null`. 
3. When the user clicks on a video list item w/ the intention to edit, we dispatch an action to set `editingVideoId`. This should also take us to a new route, like `/video/:id/edit`. This `VideoEditForm` needs to take in as a prop a `video`.
4. There should be a selector `editingVideo` that is a `createSelector` selector. It will take as its input a selector that grabs the `editingVideoId` and selectors that give it the list of videos loaded on the FE. Given these inputs it can retrieve the video record that is being edited. (Note: to make this lookup quicker we can first create a selector that, given the video list, creates a map of `[id]: VideoRecord`. The creation of this map one time (per unique list of videos) will offload the work of searching through the videos list. Then this map can be used in the `editingVideoSelector`)

EDIT: actually, I don't think we even need to keep `editingVideoId` in the redux store. We can depend on the id in the url (i.e. `video/:id/edit`. The `<VideoEditFormContainer />` can, via `mapStateToProps`, grab the `:id` from the route, and then use that to pull a video from the map of available videos. The reason `:id` will be available in `mapStateToProps` is that not only is the redux `state` available in that function, but also the component's `ownProps`; so if we, for example, have wrapped our container like so:

```javascript
<Route path={'video/:id/edit'}>
  <VideoEditFormContainer />
</Route>
```

Then here we can access:

```javascript
// VideoFormContainer.js
import { getMapOfAllVideos } from 'selectors/VideoSelectors.js';


const mapStateToProps = (state, ownProps) => ({
  video: getMapOfAllVideos(state).get(ownProps.match.params.id); // or something close to this
});


```

**Comment by jellegerbrandy** [comment]
Is there anything against having the current video in the global state, though?

In any case, the global state could could like this:

```
{
   **videos**: { // this is the list of videos that the user has "visited" or somehow sees/seen in the ap
        videoId1: {
           ... info about the video - including its state (being uploaded, downloaded, blabla...
       },
      vid2: {
     }...
    }
   **selectedVideo**: videoId2, // the video that si currently "in focus" - being edited, being shown in the palyer, etc,

    **user**: {
         // info about the current user
    },
   

}

**Comment by bent0b0x** [comment]
@jellegerbrandy it is a duplication of data. If we just store the id, we eliminate the risk of having the same video being represented differently in two (or more places) in the app
