### ISSUE TITLE
Refactor many Containers

### ISSUE THREAD

**Issue by eliawk** [Paratii-Video/paratii-portal#99]
We need to refactor many containers as [`LoginFormContainer.js`](https://github.com/Paratii-Video/paratii-portal/blob/dev/src/scripts/containers/LoginFormContainer.js), because they have `render()` function and other component related logic.

Maybe would be good also to organize the component in folder where are related to something (for example the upload flow).

**Comment by jellegerbrandy** [comment]
closing this as it is too generic. But we should make things better as we are working on the code!
